<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Career;
use App\Models\Field;

class ITDigitalTechnologyCareerSeeder extends Seeder
{
    public function run(): void
    {
        $fieldSlug = 'it-digital-technology';
        $field = Field::where('slug', $fieldSlug)->first();

        if (!$field) {
            $this->command->error("Field not found: {$fieldSlug}");
            return;
        }

        $careers = [
            [
                'slug' => 'devops-engineer',
                'title' => 'DevOps Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Cloud, DevOps & Infrastructure',
                'short_info' => 'DevOps Engineers connect software development and IT operations by automating deployment, managing CI/CD pipelines, and improving system reliability.',
                'salary_range' => '₹5L – ₹20L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / BCA / MCA / Computer Science degree or relevant certification',
                'preferred_stream' => 'Science / IT / Computer Science',
                'entrance_exams' => 'JEE Main, MHT CET, CUET UG, GATE for higher studies',
                'key_skills' => 'Linux, CI/CD, Docker, Kubernetes, Cloud Platforms, Automation',
                'top_employers' => 'IT Companies, Cloud Companies, SaaS Firms, FinTech, Product Startups',
                'image' => 'images/careers/it-digital-technology/devops-engineer.svg'
            ],
            [
                'slug' => 'machine-learning-engineer',
                'title' => 'Machine Learning Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'AI, Machine Learning & Data Science',
                'short_info' => 'Machine Learning Engineers build intelligent models that learn from data and power applications like recommendations, prediction systems, fraud detection, and automation.',
                'salary_range' => '₹6L – ₹25L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / BCA / MCA / Data Science / AI-ML specialization',
                'preferred_stream' => 'Science / IT / Computer Science',
                'entrance_exams' => 'JEE Main, MHT CET, CUET UG, GATE',
                'key_skills' => 'Python, Machine Learning, Statistics, Data Modelling, TensorFlow, Scikit-learn',
                'top_employers' => 'AI Startups, IT Product Companies, FinTech, Healthcare Tech, E-commerce',
                'image' => 'images/careers/it-digital-technology/machine-learning-engineer.svg'
            ],
            [
                'slug' => 'deep-learning-engineer',
                'title' => 'Deep Learning Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'AI, Machine Learning & Data Science',
                'short_info' => 'Deep Learning Engineers work on neural networks for image recognition, speech processing, natural language systems, and advanced AI applications.',
                'salary_range' => '₹7L – ₹28L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / M.Tech / MCA / AI-ML specialization',
                'preferred_stream' => 'Science / Computer Science / IT',
                'entrance_exams' => 'JEE Main, GATE, CUET UG',
                'key_skills' => 'Neural Networks, Python, PyTorch, TensorFlow, GPU Computing, Research',
                'top_employers' => 'AI Labs, Research Firms, Product Companies, Autonomous Systems, Healthcare AI',
                'image' => 'images/careers/it-digital-technology/deep-learning-engineer.svg'
            ],
            [
                'slug' => 'nlp-engineer',
                'title' => 'NLP Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'AI, Machine Learning & Data Science',
                'short_info' => 'NLP Engineers build systems that understand human language, such as chatbots, translation tools, search systems, and text analytics platforms.',
                'salary_range' => '₹6L – ₹24L',
                'demand_level' => 'High',
                'qualification' => 'B.Tech / MCA / Data Science / AI specialization',
                'preferred_stream' => 'Science / IT / Computer Science',
                'entrance_exams' => 'JEE Main, CUET UG, GATE',
                'key_skills' => 'Python, NLP, LLMs, Text Processing, Transformers, Data Cleaning',
                'top_employers' => 'AI Companies, Chatbot Firms, EdTech, Search Platforms, SaaS Companies',
                'image' => 'images/careers/it-digital-technology/nlp-engineer.svg'
            ],
            [
                'slug' => 'computer-vision-engineer',
                'title' => 'Computer Vision Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'AI, Machine Learning & Data Science',
                'short_info' => 'Computer Vision Engineers create systems that analyse images and videos for applications like face recognition, medical imaging, surveillance, and automation.',
                'salary_range' => '₹6L – ₹25L',
                'demand_level' => 'High',
                'qualification' => 'B.Tech / M.Tech / MCA / AI-ML specialization',
                'preferred_stream' => 'Science / Computer Science / Electronics',
                'entrance_exams' => 'JEE Main, MHT CET, GATE',
                'key_skills' => 'OpenCV, Python, Deep Learning, Image Processing, Object Detection, Algorithms',
                'top_employers' => 'AI Startups, Robotics Firms, Healthcare Tech, Security Tech, Automotive Companies',
                'image' => 'images/careers/it-digital-technology/computer-vision-engineer.svg'
            ],
            [
                'slug' => 'data-engineer',
                'title' => 'Data Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'AI, Machine Learning & Data Science',
                'short_info' => 'Data Engineers build data pipelines, databases, warehouses, and systems that help companies collect, clean, and use large volumes of data.',
                'salary_range' => '₹5L – ₹22L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / BCA / MCA / Data Engineering certification',
                'preferred_stream' => 'Science / IT / Computer Science',
                'entrance_exams' => 'JEE Main, CUET UG, GATE',
                'key_skills' => 'SQL, Python, ETL, Big Data, Spark, Cloud Data Platforms',
                'top_employers' => 'IT Companies, Banks, E-commerce, Analytics Firms, SaaS Companies',
                'image' => 'images/careers/it-digital-technology/data-engineer.svg'
            ],
            [
                'slug' => 'data-analyst',
                'title' => 'Data Analyst',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'AI, Machine Learning & Data Science',
                'short_info' => 'Data Analysts study business data, create reports, dashboards, and insights to support decision-making.',
                'salary_range' => '₹3L – ₹12L',
                'demand_level' => 'Very High',
                'qualification' => 'Graduation with analytics skills / BCA / B.Sc / B.Com / B.Tech',
                'preferred_stream' => 'Any Stream with Maths/Analytics',
                'entrance_exams' => 'CUET UG, analytics certifications',
                'key_skills' => 'Excel, SQL, Power BI, Tableau, Statistics, Data Storytelling',
                'top_employers' => 'IT Companies, Banks, Startups, Consulting Firms, E-commerce',
                'image' => 'images/careers/it-digital-technology/data-analyst.svg'
            ],
            [
                'slug' => 'bi-analyst',
                'title' => 'BI Analyst',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'AI, Machine Learning & Data Science',
                'short_info' => 'BI Analysts use business intelligence tools to convert data into dashboards, reports, and actionable business insights.',
                'salary_range' => '₹4L – ₹14L',
                'demand_level' => 'High',
                'qualification' => 'BCA / B.Tech / B.Com / MBA Analytics / Data Analytics certification',
                'preferred_stream' => 'Commerce / IT / Computer Science',
                'entrance_exams' => 'CUET UG, MBA entrance exams, analytics certifications',
                'key_skills' => 'Power BI, Tableau, SQL, Excel, Dashboard Design, Business Reporting',
                'top_employers' => 'Corporates, IT Services, Banks, Retail, Consulting Firms',
                'image' => 'images/careers/it-digital-technology/bi-analyst.svg'
            ],
            [
                'slug' => 'ai-product-manager',
                'title' => 'AI Product Manager',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Product & Solution Architecture',
                'short_info' => 'AI Product Managers plan and manage AI-powered products by connecting user needs, business goals, data teams, and engineering teams.',
                'salary_range' => '₹10L – ₹35L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / MBA / AI or Product Management certification',
                'preferred_stream' => 'IT / Management / Computer Science',
                'entrance_exams' => 'CAT, GMAT, JEE Main, Product certifications',
                'key_skills' => 'Product Strategy, AI Basics, User Research, Analytics, Communication',
                'top_employers' => 'AI Startups, SaaS Companies, FinTech, EdTech, Product Companies',
                'image' => 'images/careers/it-digital-technology/ai-product-manager.svg'
            ],
            [
                'slug' => 'prompt-engineer',
                'title' => 'Prompt Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'AI, Machine Learning & Data Science',
                'short_info' => 'Prompt Engineers design and test prompts for AI tools, chatbots, automation systems, and generative AI workflows.',
                'salary_range' => '₹4L – ₹18L',
                'demand_level' => 'Growing',
                'qualification' => 'Graduation with AI tools knowledge / Technical or communication background',
                'preferred_stream' => 'IT / Arts / Commerce / Any Stream',
                'entrance_exams' => 'No mandatory entrance exam; AI certifications useful',
                'key_skills' => 'Prompt Writing, Generative AI, Logic, Communication, Testing, Workflow Design',
                'top_employers' => 'AI Startups, Content Tech, EdTech, SaaS Companies, Automation Agencies',
                'image' => 'images/careers/it-digital-technology/prompt-engineer.svg'
            ],
            [
                'slug' => 'mlops-engineer',
                'title' => 'MLOps Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Cloud, DevOps & Infrastructure',
                'short_info' => 'MLOps Engineers deploy, monitor, and maintain machine learning models in production environments.',
                'salary_range' => '₹7L – ₹28L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / MCA / AI-ML / DevOps certification',
                'preferred_stream' => 'IT / Computer Science / Engineering',
                'entrance_exams' => 'JEE Main, GATE, CUET UG',
                'key_skills' => 'ML Pipelines, Docker, Kubernetes, Cloud, Model Monitoring, Python',
                'top_employers' => 'AI Companies, FinTech, SaaS Firms, Cloud Companies, Product Startups',
                'image' => 'images/careers/it-digital-technology/mlops-engineer.svg'
            ],
            [
                'slug' => 'site-reliability-engineer',
                'title' => 'Site Reliability Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Cloud, DevOps & Infrastructure',
                'short_info' => 'Site Reliability Engineers keep large-scale systems fast, reliable, secure, and available through automation and monitoring.',
                'salary_range' => '₹8L – ₹30L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / MCA / Computer Science / DevOps certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'JEE Main, GATE, CUET UG',
                'key_skills' => 'Linux, Monitoring, Cloud, Automation, Incident Response, Scripting',
                'top_employers' => 'Product Companies, Cloud Platforms, SaaS Firms, FinTech, Large IT Companies',
                'image' => 'images/careers/it-digital-technology/site-reliability-engineer.svg'
            ],
            [
                'slug' => 'backend-developer',
                'title' => 'Backend Developer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Software Development',
                'short_info' => 'Backend Developers build server-side logic, databases, APIs, authentication systems, and application architecture.',
                'salary_range' => '₹4L – ₹18L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / BCA / MCA / Coding skills',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'JEE Main, CUET UG, coding certifications',
                'key_skills' => 'APIs, Databases, Node.js, Java, Python, PHP, System Design',
                'top_employers' => 'IT Companies, SaaS Firms, Startups, E-commerce, FinTech',
                'image' => 'images/careers/it-digital-technology/backend-developer.svg'
            ],
            [
                'slug' => 'frontend-developer',
                'title' => 'Frontend Developer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Web Development',
                'short_info' => 'Frontend Developers build the visible part of websites and web apps using layouts, interactions, and responsive design.',
                'salary_range' => '₹3L – ₹14L',
                'demand_level' => 'Very High',
                'qualification' => 'BCA / B.Tech / Web Development certification',
                'preferred_stream' => 'IT / Computer Science / Any Stream with coding',
                'entrance_exams' => 'CUET UG, JEE Main, coding certifications',
                'key_skills' => 'HTML, CSS, JavaScript, React, UI Design, Responsive Design',
                'top_employers' => 'Web Agencies, IT Companies, Product Startups, E-commerce, SaaS Firms',
                'image' => 'images/careers/it-digital-technology/frontend-developer.svg'
            ],
            [
                'slug' => 'mobile-app-developer',
                'title' => 'Mobile App Developer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Mobile App Development',
                'short_info' => 'Mobile App Developers build applications for smartphones and tablets using Android, iOS, or cross-platform frameworks.',
                'salary_range' => '₹4L – ₹18L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / BCA / MCA / App Development certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'JEE Main, CUET UG, coding certifications',
                'key_skills' => 'Android, iOS, Flutter, APIs, UI Design, App Testing',
                'top_employers' => 'App Development Companies, Startups, IT Companies, E-commerce, FinTech',
                'image' => 'images/careers/it-digital-technology/mobile-app-developer.svg'
            ],
            [
                'slug' => 'android-developer',
                'title' => 'Android Developer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Mobile App Development',
                'short_info' => 'Android Developers create mobile apps for Android devices using Kotlin, Java, Android Studio, APIs, and mobile UI principles.',
                'salary_range' => '₹4L – ₹16L',
                'demand_level' => 'High',
                'qualification' => 'BCA / B.Tech / MCA / Android Development certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CUET UG, JEE Main, coding certifications',
                'key_skills' => 'Kotlin, Java, Android Studio, Firebase, APIs, App Testing',
                'top_employers' => 'Mobile App Firms, Startups, IT Services, Product Companies, FinTech',
                'image' => 'images/careers/it-digital-technology/android-developer.svg'
            ],
            [
                'slug' => 'ios-developer',
                'title' => 'iOS Developer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Mobile App Development',
                'short_info' => 'iOS Developers build apps for iPhone and iPad using Swift, Xcode, APIs, and Apple platform design standards.',
                'salary_range' => '₹5L – ₹20L',
                'demand_level' => 'High',
                'qualification' => 'B.Tech / BCA / MCA / iOS Development certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CUET UG, JEE Main, coding certifications',
                'key_skills' => 'Swift, Xcode, iOS SDK, APIs, App Store Deployment, UI Design',
                'top_employers' => 'App Companies, Product Startups, FinTech, E-commerce, SaaS Firms',
                'image' => 'images/careers/it-digital-technology/ios-developer.svg'
            ],
            [
                'slug' => 'flutter-developer',
                'title' => 'Flutter Developer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Mobile App Development',
                'short_info' => 'Flutter Developers build cross-platform mobile apps for Android and iOS using Flutter and Dart.',
                'salary_range' => '₹4L – ₹16L',
                'demand_level' => 'High',
                'qualification' => 'B.Tech / BCA / MCA / Flutter certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CUET UG, JEE Main, coding certifications',
                'key_skills' => 'Flutter, Dart, Firebase, APIs, UI Design, State Management',
                'top_employers' => 'Startups, App Agencies, IT Companies, SaaS Firms, EdTech',
                'image' => 'images/careers/it-digital-technology/flutter-developer.svg'
            ],
            [
                'slug' => 'react-developer',
                'title' => 'React Developer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Web Development',
                'short_info' => 'React Developers build fast and interactive web interfaces using React, JavaScript, APIs, and frontend architecture.',
                'salary_range' => '₹4L – ₹18L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / BCA / MCA / Frontend Development certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CUET UG, JEE Main, coding certifications',
                'key_skills' => 'React, JavaScript, HTML, CSS, APIs, State Management',
                'top_employers' => 'IT Companies, SaaS Firms, Startups, Product Companies, E-commerce',
                'image' => 'images/careers/it-digital-technology/react-developer.svg'
            ],
            [
                'slug' => 'laravel-developer',
                'title' => 'Laravel Developer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Web Development',
                'short_info' => 'Laravel Developers build secure and scalable web applications using PHP, Laravel, MySQL, APIs, and MVC architecture.',
                'salary_range' => '₹3L – ₹14L',
                'demand_level' => 'High',
                'qualification' => 'BCA / B.Tech / MCA / PHP-Laravel skills',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CUET UG, JEE Main, coding certifications',
                'key_skills' => 'PHP, Laravel, MySQL, APIs, MVC, Git',
                'top_employers' => 'Web Agencies, SaaS Firms, IT Services, Startups, Freelance Projects',
                'image' => 'images/careers/it-digital-technology/laravel-developer.svg'
            ],
            [
                'slug' => 'wordpress-developer',
                'title' => 'WordPress Developer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Web Development',
                'short_info' => 'WordPress Developers create websites, themes, plugins, landing pages, and CMS-based solutions for businesses.',
                'salary_range' => '₹2.5L – ₹10L',
                'demand_level' => 'High',
                'qualification' => 'Graduation / Web Development certification / Portfolio',
                'preferred_stream' => 'Any Stream with Web Skills',
                'entrance_exams' => 'No mandatory entrance exam',
                'key_skills' => 'WordPress, PHP, HTML, CSS, SEO Basics, Elementor, Theme Customization',
                'top_employers' => 'Digital Agencies, SMEs, Freelance Market, Web Development Firms',
                'image' => 'images/careers/it-digital-technology/wordpress-developer.svg'
            ],
            [
                'slug' => 'qa-tester',
                'title' => 'QA Tester',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Testing & Quality Assurance',
                'short_info' => 'QA Testers check software quality by finding bugs, testing features, and ensuring applications work correctly.',
                'salary_range' => '₹3L – ₹10L',
                'demand_level' => 'High',
                'qualification' => 'BCA / B.Tech / MCA / Software Testing certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CUET UG, JEE Main, testing certifications',
                'key_skills' => 'Manual Testing, Test Cases, Bug Reporting, SDLC, Communication',
                'top_employers' => 'IT Companies, Product Firms, SaaS Companies, Gaming Companies',
                'image' => 'images/careers/it-digital-technology/qa-tester.svg'
            ],
            [
                'slug' => 'software-tester',
                'title' => 'Software Tester',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Testing & Quality Assurance',
                'short_info' => 'Software Testers verify applications, websites, APIs, and systems to ensure they meet business and technical requirements.',
                'salary_range' => '₹3L – ₹12L',
                'demand_level' => 'High',
                'qualification' => 'BCA / B.Tech / MCA / Testing certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CUET UG, JEE Main, testing certifications',
                'key_skills' => 'Manual Testing, API Testing, Test Planning, Bug Tracking, SQL Basics',
                'top_employers' => 'IT Services, Product Companies, Banks, SaaS Firms, Startups',
                'image' => 'images/careers/it-digital-technology/software-tester.svg'
            ],
            [
                'slug' => 'automation-tester',
                'title' => 'Automation Tester',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Testing & Quality Assurance',
                'short_info' => 'Automation Testers create automated test scripts to quickly test software applications and reduce manual testing effort.',
                'salary_range' => '₹4L – ₹16L',
                'demand_level' => 'Very High',
                'qualification' => 'BCA / B.Tech / MCA / Automation Testing certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CUET UG, JEE Main, testing certifications',
                'key_skills' => 'Selenium, Java/Python, Test Automation, API Testing, CI/CD',
                'top_employers' => 'IT Companies, SaaS Firms, Product Companies, FinTech, E-commerce',
                'image' => 'images/careers/it-digital-technology/automation-tester.svg'
            ],
            [
                'slug' => 'penetration-tester',
                'title' => 'Penetration Tester',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Cyber Security',
                'short_info' => 'Penetration Testers ethically attack systems, websites, and networks to find security weaknesses before hackers exploit them.',
                'salary_range' => '₹5L – ₹22L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / BCA / MCA / Cyber Security certifications',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CEH, Security+, OSCP certifications, JEE Main optional',
                'key_skills' => 'Ethical Hacking, Web Security, Network Security, Linux, Reporting',
                'top_employers' => 'Cybersecurity Firms, Banks, IT Companies, Government Projects, FinTech',
                'image' => 'images/careers/it-digital-technology/penetration-tester.svg'
            ],
            [
                'slug' => 'security-analyst',
                'title' => 'Security Analyst',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Cyber Security',
                'short_info' => 'Security Analysts monitor systems, detect threats, analyse risks, and help protect company data and networks.',
                'salary_range' => '₹4L – ₹16L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / BCA / MCA / Cyber Security certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'Security+, CEH, cyber certifications',
                'key_skills' => 'Threat Analysis, SIEM, Network Security, Incident Response, Risk Assessment',
                'top_employers' => 'IT Security Firms, Banks, SOC Centers, Cloud Companies, Government Projects',
                'image' => 'images/careers/it-digital-technology/security-analyst.svg'
            ],
            [
                'slug' => 'soc-analyst',
                'title' => 'SOC Analyst',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Cyber Security',
                'short_info' => 'SOC Analysts work in Security Operations Centers to monitor alerts, investigate threats, and respond to cyber incidents.',
                'salary_range' => '₹3.5L – ₹14L',
                'demand_level' => 'High',
                'qualification' => 'BCA / B.Tech / MCA / Cybersecurity training',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'Security+, CEH, SOC certifications',
                'key_skills' => 'SIEM, Log Analysis, Incident Response, Threat Detection, Networking',
                'top_employers' => 'SOC Centers, Cybersecurity Firms, Banks, IT Companies, Managed Security Providers',
                'image' => 'images/careers/it-digital-technology/soc-analyst.svg'
            ],
            [
                'slug' => 'ethical-hacker',
                'title' => 'Ethical Hacker',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Cyber Security',
                'short_info' => 'Ethical Hackers legally test systems, applications, and networks to identify vulnerabilities and improve security.',
                'salary_range' => '₹4L – ₹20L',
                'demand_level' => 'Very High',
                'qualification' => 'Graduation with cybersecurity skills / CEH or related certification',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CEH, OSCP, Security+ certifications',
                'key_skills' => 'Hacking Tools, Linux, Web Security, Networking, Vulnerability Assessment',
                'top_employers' => 'Cybersecurity Firms, Banks, IT Companies, Government Security Projects',
                'image' => 'images/careers/it-digital-technology/ethical-hacker.svg'
            ],
            [
                'slug' => 'digital-forensics-analyst',
                'title' => 'Digital Forensics Analyst',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Cyber Security',
                'short_info' => 'Digital Forensics Analysts recover, analyse, and preserve digital evidence from devices, networks, and cybercrime cases.',
                'salary_range' => '₹4L – ₹18L',
                'demand_level' => 'Growing',
                'qualification' => 'B.Tech / BCA / MCA / Cyber Forensics certification',
                'preferred_stream' => 'IT / Computer Science / Forensics',
                'entrance_exams' => 'Cyber Forensics certifications, university entrance exams',
                'key_skills' => 'Digital Evidence, Forensic Tools, Cyber Law, Investigation, Report Writing',
                'top_employers' => 'Cybercrime Cells, Forensic Labs, Security Firms, Banks, Consulting Firms',
                'image' => 'images/careers/it-digital-technology/digital-forensics-analyst.svg'
            ],
            [
                'slug' => 'network-security-engineer',
                'title' => 'Network Security Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Cyber Security',
                'short_info' => 'Network Security Engineers design and protect secure networks using firewalls, VPNs, monitoring tools, and access controls.',
                'salary_range' => '₹5L – ₹20L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / BCA / MCA / Networking and security certifications',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'CCNA, CCNP Security, Security+, CEH',
                'key_skills' => 'Firewalls, VPN, Network Security, Routing, Switching, Monitoring',
                'top_employers' => 'Telecom, IT Companies, Banks, Cloud Firms, Cybersecurity Companies',
                'image' => 'images/careers/it-digital-technology/network-security-engineer.svg'
            ],
            [
                'slug' => 'cloud-architect',
                'title' => 'Cloud Architect',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Cloud, DevOps & Infrastructure',
                'short_info' => 'Cloud Architects design cloud infrastructure, migration plans, security models, and scalable systems for companies.',
                'salary_range' => '₹12L – ₹40L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / MCA / Cloud certifications with experience',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'AWS, Azure, Google Cloud certifications',
                'key_skills' => 'Cloud Architecture, AWS/Azure/GCP, Security, Networking, Cost Optimization',
                'top_employers' => 'Cloud Companies, IT Services, Product Firms, Banks, Enterprise Companies',
                'image' => 'images/careers/it-digital-technology/cloud-architect.svg'
            ],
            [
                'slug' => 'solutions-architect',
                'title' => 'Solutions Architect',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Product & Solution Architecture',
                'short_info' => 'Solutions Architects design complete technical solutions by combining software, cloud, databases, security, and business requirements.',
                'salary_range' => '₹12L – ₹40L',
                'demand_level' => 'Very High',
                'qualification' => 'B.Tech / MCA / Technical experience / Cloud certifications',
                'preferred_stream' => 'IT / Computer Science',
                'entrance_exams' => 'Cloud certifications, architecture certifications',
                'key_skills' => 'System Design, Cloud, APIs, Databases, Communication, Technical Planning',
                'top_employers' => 'IT Companies, SaaS Firms, Cloud Providers, Enterprise Technology Companies',
                'image' => 'images/careers/it-digital-technology/solutions-architect.svg'
            ],
            [
                'slug' => 'erp-consultant',
                'title' => 'ERP Consultant',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Enterprise Technology',
                'short_info' => 'ERP Consultants implement and customize enterprise software like SAP, Oracle, Microsoft Dynamics, or Odoo for business operations.',
                'salary_range' => '₹5L – ₹22L',
                'demand_level' => 'High',
                'qualification' => 'B.Com / BBA / B.Tech / MBA / ERP certification',
                'preferred_stream' => 'Commerce / IT / Management',
                'entrance_exams' => 'ERP certifications, MBA entrance exams optional',
                'key_skills' => 'Business Processes, ERP Modules, SAP/Oracle/Odoo, Configuration, Client Communication',
                'top_employers' => 'Consulting Firms, IT Companies, Manufacturing, Retail, Large Enterprises',
                'image' => 'images/careers/it-digital-technology/erp-consultant.svg'
            ],
            [
                'slug' => 'crm-developer',
                'title' => 'CRM Developer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Enterprise Technology',
                'short_info' => 'CRM Developers customize customer relationship management platforms like Salesforce, Zoho, HubSpot, or Microsoft Dynamics.',
                'salary_range' => '₹4L – ₹18L',
                'demand_level' => 'High',
                'qualification' => 'BCA / B.Tech / MCA / CRM platform certification',
                'preferred_stream' => 'IT / Computer Science / Management',
                'entrance_exams' => 'Salesforce/Zoho/CRM certifications',
                'key_skills' => 'CRM Platforms, APIs, Automation, JavaScript, Business Workflows',
                'top_employers' => 'CRM Consulting Firms, SaaS Companies, IT Services, Sales Tech Companies',
                'image' => 'images/careers/it-digital-technology/crm-developer.svg'
            ],
            [
                'slug' => 'technical-support-engineer',
                'title' => 'Technical Support Engineer',
                'category' => 'IT & Digital Technology',
                'sub_domain' => 'Technical Support & IT Services',
                'short_info' => 'Technical Support Engineers help users resolve software, hardware, network, and application issues through troubleshooting and guidance.',
                'salary_range' => '₹2.5L – ₹8L',
                'demand_level' => 'High',
                'qualification' => 'Diploma / BCA / B.Tech / IT certification',
                'preferred_stream' => 'IT / Computer Science / Technical',
                'entrance_exams' => 'No mandatory entrance exam; CompTIA/Networking certifications useful',
                'key_skills' => 'Troubleshooting, Communication, Networking Basics, Customer Support, Documentation',
                'top_employers' => 'IT Services, SaaS Companies, Hardware Firms, BPO/KPO, Enterprise Support Teams',
                'image' => 'images/careers/it-digital-technology/technical-support-engineer.svg'
            ]
        ];

        $roadmap = "Step 1: Complete 10+2 preferably with Mathematics, Computer Science, or Science stream.\nStep 2: Pursue B.Tech / BCA / B.Sc CS / MCA / Diploma / relevant IT course.\nStep 3: Learn core tools such as programming, databases, cloud, cybersecurity, AI, or testing based on the career.\nStep 4: Build projects, GitHub portfolio, internships, certifications, or freelance experience.\nStep 5: Apply for entry-level roles such as trainee developer, analyst, tester, support engineer, or junior engineer.\nStep 6: Grow into senior engineer, architect, product lead, manager, consultant, or specialist roles.";
        $future_scope = "IT careers have strong future scope because AI, cloud computing, cybersecurity, data, mobile apps, automation, and digital transformation are growing across industries.";

        foreach ($careers as $careerData) {
            Career::updateOrCreate(
                ['slug' => $careerData['slug']],
                [
                    'field_id' => $field->id,
                    'name' => $careerData['title'],
                    'sub_domain' => $careerData['sub_domain'],
                    'description' => $careerData['short_info'],
                    'salary_range' => $careerData['salary_range'],
                    'demand_level' => $careerData['demand_level'],
                    'qualification' => $careerData['qualification'],
                    'stream' => $careerData['preferred_stream'],
                    'skills' => array_map('trim', explode(',', $careerData['key_skills'])),
                    'entrance_exams' => array_map('trim', explode(',', $careerData['entrance_exams'])),
                    'roadmap' => array_filter(array_map('trim', explode("\n", $roadmap))),
                    'future_scope' => $future_scope,
                    'job_opportunities' => array_map('trim', explode(',', $careerData['top_employers'])),
                    'image' => $careerData['image']
                ]
            );
        }

        $this->command->info('IT & Digital Technology careers seeded successfully.');
    }
}
