<?php

namespace Database\Seeders;

use App\Models\Career;
use App\Models\Field;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MassCareersExpansionSeeder2 extends Seeder
{
    public function run(): void
    {
        $fields = [
            'Operations' => Field::where('slug', 'hospitality-aviation-tourism-logistics')->first(),
            'Law' => Field::where('slug', 'education-social-law-policy')->first(),
            'Science' => Field::where('slug', 'science')->first(),
            'Trades' => Field::where('slug', 'skill-trades-manufacturing-retail')->first(),
        ];

        $careers = [
            // ==================================================
            // CATEGORY: Operations, Logistics & Hospitality
            // ==================================================
            ['title' => 'Air Hostess/Purser', 'cat' => 'Operations', 'domain' => 'Aviation', 'short' => 'Ensures the safety and comfort of passengers on commercial flights.', 'salary' => '₹4L - ₹10L per annum', 'demand' => 'High', 'qual' => '12th Pass + Cabin Crew Training', 'stream' => 'Any Stream', 'exams' => ['Airline Interviews'], 'skills' => ['Communication', 'Customer Service', 'Emergency Handling'], 'employers' => ['IndiGo', 'Air India', 'Vistara']],
            ['title' => 'Air Traffic Controller', 'cat' => 'Operations', 'domain' => 'Aviation', 'short' => 'Directs aircraft movements in airspace and on the ground.', 'salary' => '₹8L - ₹18L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech/B.Sc (Physics/Maths)', 'stream' => 'Science (PCM)', 'exams' => ['AAI ATC Exam'], 'skills' => ['Concentration', 'Decision Making', 'Communication'], 'employers' => ['Airports Authority of India (AAI)']],
            ['title' => 'Aircraft Pilot', 'cat' => 'Operations', 'domain' => 'Aviation', 'short' => 'Flies and navigates airplanes, helicopters, and other aircraft.', 'salary' => '₹15L - ₹40L+ per annum', 'demand' => 'High', 'qual' => 'Commercial Pilot License (CPL)', 'stream' => 'Science (PCM)', 'exams' => ['DGCA Exams', 'Medical Class 1'], 'skills' => ['Aviation Knowledge', 'Quick Reflexes', 'Leadership'], 'employers' => ['Commercial Airlines', 'Charter Companies']],
            ['title' => 'Airline Cargo Assistant', 'cat' => 'Operations', 'domain' => 'Aviation/Logistics', 'short' => 'Manages the loading, unloading, and tracking of air cargo.', 'salary' => '₹2.5L - ₹5L per annum', 'demand' => 'Stable', 'qual' => '12th Pass / Graduation', 'stream' => 'Any Stream', 'exams' => ['Company Interviews'], 'skills' => ['Logistics', 'Physical Stamina', 'Record Keeping'], 'employers' => ['Blue Dart Aviation', 'Airline Cargo Depts']],
            ['title' => 'Airline Customer Service Executive', 'cat' => 'Operations', 'domain' => 'Aviation', 'short' => 'Assists passengers with ticketing, check-in, and boarding.', 'salary' => '₹3L - ₹6L per annum', 'demand' => 'High', 'qual' => 'Graduation / Diploma in Aviation', 'stream' => 'Any Stream', 'exams' => ['Interviews'], 'skills' => ['Customer Service', 'Communication', 'Patience'], 'employers' => ['IndiGo', 'Air India', 'SpiceJet']],
            ['title' => 'Airline Ground Support Equipment Operator', 'cat' => 'Operations', 'domain' => 'Aviation', 'short' => 'Operates vehicles and equipment for aircraft servicing on the ground.', 'salary' => '₹2.5L - ₹5L per annum', 'demand' => 'Stable', 'qual' => '10th/12th + Heavy Vehicle License', 'stream' => 'Any Stream', 'exams' => ['Skill Test'], 'skills' => ['Driving', 'Safety Protocols', 'Equipment Maintenance'], 'employers' => ['Ground Handling Agencies (AISATS, Celebi)']],
            ['title' => 'Auctioneer', 'cat' => 'Operations', 'domain' => 'Sales', 'short' => 'Conducts public sales where goods or property are sold to the highest bidder.', 'salary' => '₹4L - ₹12L per annum (Commission based)', 'demand' => 'Stable', 'qual' => 'Graduation (Any)', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Public Speaking', 'Valuation', 'Sales'], 'employers' => ['Auction Houses', 'Real Estate Firms']],
            ['title' => 'Bartender/Mixologist', 'cat' => 'Operations', 'domain' => 'Hospitality', 'short' => 'Prepares and serves beverages, creating new drink recipes.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'High', 'qual' => 'Diploma in Bartending/Hotel Mgt', 'stream' => 'Any Stream', 'exams' => ['Skill Certification'], 'skills' => ['Mixology', 'Customer Service', 'Memory'], 'employers' => ['Hotels', 'Bars/Pubs', 'Cruise Lines']],
            ['title' => 'Bulldozer Operator', 'cat' => 'Operations', 'domain' => 'Construction/Logistics', 'short' => 'Operates heavy machinery to clear land and move materials.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'Stable', 'qual' => '10th Pass + Heavy Machine License', 'stream' => 'Any Stream', 'exams' => ['Skill Test'], 'skills' => ['Machine Operation', 'Safety', 'Coordination'], 'employers' => ['Construction Firms', 'Mining Companies']],
            ['title' => 'Cold Chain Process Management Specialist', 'cat' => 'Operations', 'domain' => 'Logistics', 'short' => 'Manages temperature-controlled supply chains for perishable goods.', 'salary' => '₹4L - ₹10L per annum', 'demand' => 'Growing', 'qual' => 'B.Tech/MBA in Supply Chain', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Logistics', 'Quality Control', 'Temperature Monitoring'], 'employers' => ['Pharma Logistics', 'FMCG', 'Snowman Logistics']],
            ['title' => 'Commercial Driver', 'cat' => 'Operations', 'domain' => 'Logistics', 'short' => 'Drives trucks, buses, or delivery vehicles for commercial purposes.', 'salary' => '₹2L - ₹5L per annum', 'demand' => 'High', 'qual' => '10th Pass + Commercial Driving License', 'stream' => 'Any Stream', 'exams' => ['RTO Driving Test'], 'skills' => ['Safe Driving', 'Vehicle Maintenance', 'Navigation'], 'employers' => ['Logistics Companies', 'Transport Firms']],
            ['title' => 'Conveyor Operation and Maintenance Technician', 'cat' => 'Operations', 'domain' => 'Manufacturing/Logistics', 'short' => 'Operates and repairs conveyor belt systems in factories or warehouses.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'Stable', 'qual' => 'ITI in Mechanical/Fitter', 'stream' => 'Science/Tech', 'exams' => ['Skill Test'], 'skills' => ['Mechanical Maintenance', 'Troubleshooting', 'Safety'], 'employers' => ['Manufacturing Plants', 'E-commerce Warehouses']],
            ['title' => 'Distribution Manager', 'cat' => 'Operations', 'domain' => 'Logistics', 'short' => 'Oversees the transportation of goods from production to the consumer.', 'salary' => '₹6L - ₹15L per annum', 'demand' => 'High', 'qual' => 'MBA in Supply Chain/Logistics', 'stream' => 'Any Stream', 'exams' => ['CAT/MAT'], 'skills' => ['Logistics Planning', 'Team Management', 'Supply Chain Software'], 'employers' => ['FMCG', 'E-commerce', 'Manufacturing']],
            ['title' => 'Food and Beverage Manager', 'cat' => 'Operations', 'domain' => 'Hospitality', 'short' => 'Plans and coordinates food and beverage service operations.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'High', 'qual' => 'Degree in Hotel Management', 'stream' => 'Any Stream', 'exams' => ['NCHMCT JEE'], 'skills' => ['Operations Management', 'Budgeting', 'Customer Experience'], 'employers' => ['5-Star Hotels', 'Large Restaurants', 'Resorts']],
            ['title' => 'Front Office Associate', 'cat' => 'Operations', 'domain' => 'Hospitality/Corporate', 'short' => 'Manages reception, greets guests, and handles administrative tasks.', 'salary' => '₹2.5L - ₹6L per annum', 'demand' => 'High', 'qual' => 'Graduation / Hotel Management Diploma', 'stream' => 'Any Stream', 'exams' => ['Interviews'], 'skills' => ['Communication', 'Hospitality', 'Multitasking'], 'employers' => ['Hotels', 'Corporate Offices', 'Hospitals']],
            ['title' => 'Logistics Analyst', 'cat' => 'Operations', 'domain' => 'Logistics', 'short' => 'Analyzes supply chain processes to identify areas for improvement.', 'salary' => '₹4L - ₹10L per annum', 'demand' => 'High', 'qual' => 'B.Tech / BBA / MBA', 'stream' => 'Any Stream with Math/Stats', 'exams' => ['None'], 'skills' => ['Data Analysis', 'Excel', 'Supply Chain Knowledge'], 'employers' => ['Delhivery', 'Amazon', 'Maersk']],
            ['title' => 'Logistics Manager', 'cat' => 'Operations', 'domain' => 'Logistics', 'short' => 'Coordinates the storage and distribution of goods.', 'salary' => '₹6L - ₹18L per annum', 'demand' => 'High', 'qual' => 'MBA in Logistics/Supply Chain', 'stream' => 'Any Stream', 'exams' => ['CAT', 'XAT'], 'skills' => ['Inventory Management', 'Transportation', 'Leadership'], 'employers' => ['Logistics Providers', 'E-commerce', 'Manufacturing']],
            ['title' => 'Multi-tasking Staff', 'cat' => 'Operations', 'domain' => 'Admin Support', 'short' => 'Performs various routine office duties and support tasks.', 'salary' => '₹1.8L - ₹3.5L per annum', 'demand' => 'High', 'qual' => '10th / 12th Pass', 'stream' => 'Any Stream', 'exams' => ['SSC MTS (for Govt)'], 'skills' => ['Basic Office Work', 'Organization', 'Assistance'], 'employers' => ['Government Departments', 'Private Offices']],
            ['title' => 'Nature Guide', 'cat' => 'Operations', 'domain' => 'Tourism', 'short' => 'Leads tours in natural areas, educating visitors about flora and fauna.', 'salary' => '₹2.5L - ₹6L per annum', 'demand' => 'Growing', 'qual' => 'Degree in Life Sciences/Forestry/Tourism', 'stream' => 'Science preferred', 'exams' => ['Skill Certification'], 'skills' => ['Wildlife Knowledge', 'Communication', 'First Aid'], 'employers' => ['National Parks', 'Eco-tourism Resorts', 'Forest Dept']],
            ['title' => 'Office Administrator', 'cat' => 'Operations', 'domain' => 'Admin Support', 'short' => 'Coordinates office activities and operations to secure efficiency.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Very High', 'qual' => 'Graduation (Any)', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Organization', 'MS Office', 'Communication'], 'employers' => ['All Corporate Sectors', 'Schools/Colleges', 'Hospitals']],
            ['title' => 'Operations Manager', 'cat' => 'Operations', 'domain' => 'Business Operations', 'short' => 'Manages the overall operations and processes of a business or facility.', 'salary' => '₹8L - ₹25L per annum', 'demand' => 'High', 'qual' => 'MBA in Operations', 'stream' => 'Any Stream', 'exams' => ['CAT', 'MAT'], 'skills' => ['Process Optimization', 'Leadership', 'Budgeting'], 'employers' => ['Manufacturing', 'IT Services', 'E-commerce']],
            ['title' => 'Package Dyeing Machine Operator', 'cat' => 'Operations', 'domain' => 'Manufacturing', 'short' => 'Operates machines to dye yarn or textiles in a manufacturing setting.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'Stable', 'qual' => 'ITI / 10th Pass', 'stream' => 'Any Stream', 'exams' => ['Skill Test'], 'skills' => ['Machine Operation', 'Color Matching', 'Safety'], 'employers' => ['Textile Mills', 'Garment Manufacturers']],
            ['title' => 'Port Operations Manager', 'cat' => 'Operations', 'domain' => 'Maritime/Logistics', 'short' => 'Oversees the daily activities and logistics at a shipping port.', 'salary' => '₹8L - ₹20L per annum', 'demand' => 'Moderate', 'qual' => 'MBA in Port/Logistics Management', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Port Logistics', 'Customs Knowledge', 'Team Management'], 'employers' => ['Adani Ports', 'JNPT', 'Shipping Agencies']],
            ['title' => 'Secretary/Personal Assistant', 'cat' => 'Operations', 'domain' => 'Admin Support', 'short' => 'Provides administrative support to executives or managers.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'High', 'qual' => 'Graduation / Secretarial Diploma', 'stream' => 'Any Stream', 'exams' => ['Stenography Tests (Govt)'], 'skills' => ['Organization', 'Scheduling', 'Communication'], 'employers' => ['Corporate Executives', 'Government Officials']],
            ['title' => 'Sommelier', 'cat' => 'Operations', 'domain' => 'Hospitality', 'short' => 'A trained wine professional specializing in all aspects of wine service.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'Sommelier Certification / Hotel Management', 'stream' => 'Any Stream', 'exams' => ['WSET Certification'], 'skills' => ['Wine Tasting', 'Pairing', 'Customer Service'], 'employers' => ['Fine Dining Restaurants', '5-Star Hotels', 'Wineries']],
            ['title' => 'Supply Chain Manager', 'cat' => 'Operations', 'domain' => 'Logistics', 'short' => 'Coordinates the entire lifecycle of a product from raw materials to consumer.', 'salary' => '₹8L - ₹22L per annum', 'demand' => 'Very High', 'qual' => 'MBA in Supply Chain Management', 'stream' => 'Any Stream', 'exams' => ['CAT', 'XAT'], 'skills' => ['Vendor Management', 'Forecasting', 'Logistics'], 'employers' => ['FMCG', 'Automotive', 'E-commerce (Amazon, Flipkart)']],
            ['title' => 'Tour Guide', 'cat' => 'Operations', 'domain' => 'Tourism', 'short' => 'Shows visitors around places of interest, providing information and history.', 'salary' => '₹2.5L - ₹6L per annum', 'demand' => 'High', 'qual' => 'Degree/Diploma in Tourism', 'stream' => 'Any Stream', 'exams' => ['Ministry of Tourism License'], 'skills' => ['Communication', 'Historical Knowledge', 'Languages'], 'employers' => ['Travel Agencies', 'Museums', 'Freelance']],
            ['title' => 'Tour Operator', 'cat' => 'Operations', 'domain' => 'Tourism', 'short' => 'Packages and sells holidays and travel itineraries.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'High', 'qual' => 'Degree/Diploma in Travel and Tourism', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Itinerary Planning', 'Sales', 'Vendor Negotiation'], 'employers' => ['MakeMyTrip', 'Thomas Cook', 'Own Business']],
            ['title' => 'Transportation Manager', 'cat' => 'Operations', 'domain' => 'Logistics', 'short' => 'Directs the dispatching, routing, and tracking of transportation vehicles.', 'salary' => '₹5L - ₹14L per annum', 'demand' => 'High', 'qual' => 'Graduation / MBA in Logistics', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Fleet Management', 'Routing', 'Cost Control'], 'employers' => ['VRL Logistics', 'Gati', 'E-commerce']],
            ['title' => 'Travel Consultant', 'cat' => 'Operations', 'domain' => 'Tourism', 'short' => 'Advises clients on travel options and books trips and accommodations.', 'salary' => '₹3L - ₹7L per annum', 'demand' => 'High', 'qual' => 'Degree/Diploma in Tourism', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['GDS (Amadeus/Galileo)', 'Customer Service', 'Geography'], 'employers' => ['Travel Agencies', 'Corporate Travel Depts', 'OTAs']],
            ['title' => 'Urban Planner', 'cat' => 'Operations', 'domain' => 'Infrastructure/Planning', 'short' => 'Develops plans and programs for land use in urban and regional areas.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'Moderate', 'qual' => 'B.Plan / M.Plan / B.Arch', 'stream' => 'Science (PCM) preferred', 'exams' => ['NATA', 'JEE Main Paper 2', 'GATE'], 'skills' => ['GIS', 'Urban Design', 'Policy Analysis'], 'employers' => ['Town Planning Departments', 'Consultancies', 'Real Estate']],

            // ==================================================
            // CATEGORY: Public Policy, Law & Safety
            // ==================================================
            ['title' => 'Arbitrator', 'cat' => 'Law', 'domain' => 'Legal', 'short' => 'An independent third party appointed to settle a dispute outside of court.', 'salary' => '₹8L - ₹25L per annum', 'demand' => 'Growing', 'qual' => 'LLB + Experience', 'stream' => 'Any Stream', 'exams' => ['CLAT'], 'skills' => ['Dispute Resolution', 'Legal Knowledge', 'Impartiality'], 'employers' => ['Arbitration Centers', 'Corporate Firms', 'Independent Practice']],
            ['title' => 'Corporate Legal Advisor/Compliance Officer', 'cat' => 'Law', 'domain' => 'Corporate Law', 'short' => 'Ensures that a company complies with all legal and regulatory requirements.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'High', 'qual' => 'LLB / CS (Company Secretary)', 'stream' => 'Any Stream', 'exams' => ['CLAT', 'ICSI Exams'], 'skills' => ['Corporate Law', 'Drafting', 'Risk Management'], 'employers' => ['MNCs', 'Banks', 'Law Firms']],
            ['title' => 'Detective', 'cat' => 'Law', 'domain' => 'Investigation', 'short' => 'Gathers facts and collects evidence for criminal cases or private clients.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'Graduation / Law / Forensic Science', 'stream' => 'Any Stream', 'exams' => ['Police Exams (for Govt)'], 'skills' => ['Investigation', 'Observation', 'Interrogation'], 'employers' => ['Private Agencies', 'Police Departments', 'CBI']],
            ['title' => 'Firefighter', 'cat' => 'Law', 'domain' => 'Safety', 'short' => 'Responds to fires, accidents, and other incidents where risks are posed to life and property.', 'salary' => '₹3L - ₹6L per annum', 'demand' => 'Stable', 'qual' => '10th/12th Pass + Firefighting Training', 'stream' => 'Any Stream', 'exams' => ['State Fire Service Exams'], 'skills' => ['Physical Fitness', 'Firefighting Tech', 'First Aid'], 'employers' => ['State Fire Services', 'Airports', 'Large Industries']],
            ['title' => 'Human Rights Lawyer', 'cat' => 'Law', 'domain' => 'Legal', 'short' => 'Specializes in cases involving the infringement of human rights.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'Moderate', 'qual' => 'LLB', 'stream' => 'Any Stream', 'exams' => ['CLAT'], 'skills' => ['Constitutional Law', 'Advocacy', 'Research'], 'employers' => ['NGOs', 'Human Rights Commissions', 'Independent Practice']],
            ['title' => 'International Relations Specialist', 'cat' => 'Law', 'domain' => 'Policy/Diplomacy', 'short' => 'Analyzes and advises on foreign policies, global issues, and international affairs.', 'salary' => '₹6L - ₹18L per annum', 'demand' => 'Moderate', 'qual' => 'MA in International Relations/Political Science', 'stream' => 'Arts/Humanities preferred', 'exams' => ['UPSC (for IFS)', 'CUET PG'], 'skills' => ['Geopolitics', 'Research', 'Languages'], 'employers' => ['Think Tanks', 'UN Agencies', 'Government']],
            ['title' => 'Judge', 'cat' => 'Law', 'domain' => 'Judiciary', 'short' => 'Presides over court proceedings to ensure the law is applied fairly.', 'salary' => '₹12L - ₹30L+ per annum', 'demand' => 'Stable', 'qual' => 'LLB + Experience / Judicial Services Exam', 'stream' => 'Any Stream', 'exams' => ['State Judicial Services Exam'], 'skills' => ['Legal Expertise', 'Impartiality', 'Decision Making'], 'employers' => ['District Courts', 'High Courts', 'Supreme Court']],
            ['title' => 'Lawyer/Law Officer/Advocate', 'cat' => 'Law', 'domain' => 'Legal', 'short' => 'Represents clients in criminal and civil litigation and other legal proceedings.', 'salary' => '₹4L - ₹20L+ per annum', 'demand' => 'High', 'qual' => 'LLB', 'stream' => 'Any Stream', 'exams' => ['CLAT', 'AIBE'], 'skills' => ['Litigation', 'Legal Drafting', 'Argumentation'], 'employers' => ['Law Firms', 'Corporate Legal Depts', 'Independent Practice']],
            ['title' => 'Medical Legal Advisor', 'cat' => 'Law', 'domain' => 'Legal/Medical', 'short' => 'Provides legal advice on medical cases, malpractice, and healthcare regulations.', 'salary' => '₹6L - ₹15L per annum', 'demand' => 'Growing', 'qual' => 'MBBS + LLB / Forensic Medicine', 'stream' => 'Science (PCB)', 'exams' => ['NEET', 'CLAT'], 'skills' => ['Medical Law', 'Ethics', 'Analysis'], 'employers' => ['Hospitals', 'Insurance Companies', 'Law Firms']],
            ['title' => 'Patent Lawyer', 'cat' => 'Law', 'domain' => 'Intellectual Property', 'short' => 'Specializes in securing and protecting patents for inventors and companies.', 'salary' => '₹8L - ₹25L per annum', 'demand' => 'High', 'qual' => 'B.Tech/M.Sc + LLB', 'stream' => 'Science', 'exams' => ['Patent Agent Exam', 'CLAT'], 'skills' => ['IP Law', 'Technical Knowledge', 'Drafting'], 'employers' => ['IP Law Firms', 'Tech Companies', 'Pharma Companies']],
            ['title' => 'Psephologist', 'cat' => 'Law', 'domain' => 'Political Science', 'short' => 'Studies and analyzes elections and voting behavior.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'Stable', 'qual' => 'Degree in Political Science/Statistics', 'stream' => 'Arts/Science', 'exams' => ['None'], 'skills' => ['Data Analysis', 'Political Knowledge', 'Polling Methodologies'], 'employers' => ['Media Houses', 'Political Consultancies', 'Think Tanks']],
            ['title' => 'Public Policy Advisor', 'cat' => 'Law', 'domain' => 'Policy', 'short' => 'Researches and develops policies to solve societal or organizational problems.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'Growing', 'qual' => 'Master\'s in Public Policy/Administration', 'stream' => 'Any Stream', 'exams' => ['Institute Specific Exams'], 'skills' => ['Policy Analysis', 'Research', 'Economics'], 'employers' => ['Think Tanks (NITI Aayog)', 'NGOs', 'Corporate Affairs']],
            ['title' => 'Social Worker', 'cat' => 'Law', 'domain' => 'Social Work', 'short' => 'Helps individuals, families, and communities cope with problems to improve their lives.', 'salary' => '₹2.5L - ₹6L per annum', 'demand' => 'Stable', 'qual' => 'BSW / MSW', 'stream' => 'Any Stream', 'exams' => ['TISSNET (CUET PG)'], 'skills' => ['Empathy', 'Case Management', 'Counseling'], 'employers' => ['NGOs', 'Hospitals', 'Government Welfare Depts']],
            ['title' => 'Sports Lawyer', 'cat' => 'Law', 'domain' => 'Legal/Sports', 'short' => 'Handles legal matters in the sports industry, including contracts and sponsorships.', 'salary' => '₹6L - ₹18L per annum', 'demand' => 'Stable', 'qual' => 'LLB + Sports Law Specialization', 'stream' => 'Any Stream', 'exams' => ['CLAT'], 'skills' => ['Contract Law', 'Negotiation', 'Sports Regulations'], 'employers' => ['Sports Agencies', 'Franchises', 'Law Firms']],
            ['title' => 'Unarmed Security Guard', 'cat' => 'Law', 'domain' => 'Safety', 'short' => 'Protects property, assets, and people without the use of firearms.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'Very High', 'qual' => '8th/10th Pass', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Observation', 'Physical Fitness', 'Basic Communication'], 'employers' => ['Private Security Agencies (SIS, G4S)', 'Residential Complexes']],

        ];

        foreach ($careers as $c) {
            $fieldModel = $fields[$c['cat']] ?? null;
            if (!$fieldModel) continue;
            
            $slug = Str::slug($c['title']);
            $roadmap = [
                "Complete 10+2 with " . $c['stream'],
                "Qualify entrance exams like " . implode(", ", $c['exams']),
                "Pursue " . $c['qual'],
                "Gain skills in " . implode(", ", $c['skills']),
                "Apply for jobs in " . implode(", ", array_slice($c['employers'], 0, 2))
            ];

            Career::firstOrCreate(
                ['slug' => $slug],
                [
                    'name' => $c['title'],
                    'field_id' => $fieldModel->id,
                    'sub_domain' => $c['domain'],
                    'description' => $c['short'],
                    'qualification' => $c['qual'],
                    'stream' => $c['stream'],
                    'salary_range' => $c['salary'],
                    'demand_level' => $c['demand'] ?? 'High',
                    'roadmap' => $roadmap,
                    'icon' => 'fa-briefcase',
                    'skills' => $c['skills'],
                    'entrance_exams' => $c['exams'],
                    'job_opportunities' => $c['employers'],
                    'image' => $slug . '.svg'
                ]
            );
        }
    }
}
