<?php

namespace Database\Seeders;

use App\Models\Career;
use App\Models\Field;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MassCareersExpansionSeeder1 extends Seeder
{
    public function run(): void
    {
        // Data mapping helper
        $fields = [
            'Engineering' => Field::where('slug', 'technology-engineering')->first(),
            'Government' => Field::where('slug', 'government-defence')->first(),
            'IT' => Field::where('slug', 'it-digital-technology')->first(),
            'Management' => Field::where('slug', 'business')->first(),
            'Operations' => Field::where('slug', 'hospitality-aviation-tourism-logistics')->first(),
            'Law' => Field::where('slug', 'education-social-law-policy')->first(),
            'Science' => Field::where('slug', 'science')->first(),
            'Trades' => Field::where('slug', 'skill-trades-manufacturing-retail')->first(),
        ];

        $careers = [
            // ==================================================
            // CATEGORY: Technology & Engineering / Engineering
            // ==================================================
            ['title' => 'Aeronautical Engineer', 'cat' => 'Engineering', 'domain' => 'Aerospace', 'short' => 'Designs and tests aircraft and aerospace systems.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Aeronautical Engineering', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'JEE Advanced', 'GATE'], 'skills' => ['Aerodynamics', 'Thermodynamics', 'CAD'], 'employers' => ['ISRO', 'DRDO', 'HAL', 'Boeing', 'Airbus']],
            ['title' => 'Automobile Engineer', 'cat' => 'Engineering', 'domain' => 'Mechanical', 'short' => 'Designs, develops and tests vehicles from concept to production.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Automobile/Mechanical Engineering', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'State CETs'], 'skills' => ['Vehicle Dynamics', 'CAD/CAM', 'Thermodynamics'], 'employers' => ['Tata Motors', 'Mahindra', 'Maruti Suzuki']],
            ['title' => 'Bioinformatics Engineering', 'cat' => 'Engineering', 'domain' => 'Biotechnology', 'short' => 'Combines biology, computer science, and data analysis to understand biological data.', 'salary' => '₹5L - ₹18L per annum', 'demand' => 'Growing', 'qual' => 'B.Tech in Bioinformatics', 'stream' => 'Science (PCB/PCM)', 'exams' => ['JEE Main', 'ICAR AIEEA'], 'skills' => ['Data Mining', 'Python/R', 'Genomics'], 'employers' => ['Biocon', 'Serum Institute', 'Research Labs']],
            ['title' => 'Biomedical Engineer', 'cat' => 'Engineering', 'domain' => 'Biotechnology', 'short' => 'Applies engineering principles to healthcare and medical device development.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Biomedical Engineering', 'stream' => 'Science (PCM/PCB)', 'exams' => ['JEE Main', 'NEET (Some institutes)'], 'skills' => ['Medical Imaging', 'Biomechanics', 'Electronics'], 'employers' => ['Siemens Healthineers', 'GE Healthcare', 'Hospitals']],
            ['title' => 'Biotechnology Engineer', 'cat' => 'Engineering', 'domain' => 'Biotechnology', 'short' => 'Uses biological systems and living organisms to develop technological products.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Biotechnology', 'stream' => 'Science (PCB/PCM)', 'exams' => ['JEE Main', 'State CETs'], 'skills' => ['Molecular Biology', 'Process Engineering', 'Genetics'], 'employers' => ['Biocon', 'Bharat Biotech', 'Agri-tech firms']],
            ['title' => 'Broadcast Engineer', 'cat' => 'Engineering', 'domain' => 'Electronics', 'short' => 'Manages technical equipment for television, radio, and digital broadcasting.', 'salary' => '₹3.5L - ₹10L per annum', 'demand' => 'Stable', 'qual' => 'B.Tech in Electronics/Communication', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Signal Processing', 'RF Engineering', 'Media Tech'], 'employers' => ['Prasar Bharati', 'News Channels', 'Radio Stations']],
            ['title' => 'CAD Designer for Carpets', 'cat' => 'Engineering', 'domain' => 'Design', 'short' => 'Uses computer-aided design software to create carpet patterns and layouts.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Stable', 'qual' => 'Diploma/B.Des or CAD Certification', 'stream' => 'Any Stream', 'exams' => ['NID DAT', 'Skill Certification'], 'skills' => ['AutoCAD', 'Textile Design', 'Pattern Making'], 'employers' => ['Textile Mills', 'Carpet Export Firms']],
            ['title' => 'CAD Jewellery Designer', 'cat' => 'Engineering', 'domain' => 'Design', 'short' => 'Creates 3D models of jewelry designs using specialized CAD software.', 'salary' => '₹3L - ₹12L per annum', 'demand' => 'High', 'qual' => 'Diploma/Degree in Jewellery Design', 'stream' => 'Any Stream', 'exams' => ['NIFT', 'Skill Certification'], 'skills' => ['Rhino', 'Matrix', '3D Modeling'], 'employers' => ['Tanishq', 'Kalyan Jewellers', 'Export Houses']],
            ['title' => 'Ceramic Technologist/Engineer', 'cat' => 'Engineering', 'domain' => 'Materials', 'short' => 'Develops materials from non-metallic, inorganic elements for various industries.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech in Ceramic Engineering', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'State CETs'], 'skills' => ['Material Science', 'Thermodynamics', 'Manufacturing'], 'employers' => ['Kajaria', 'Somany', 'Glass Industries']],
            ['title' => 'Chemical Engineer', 'cat' => 'Engineering', 'domain' => 'Chemical', 'short' => 'Designs and develops chemical manufacturing processes.', 'salary' => '₹5L - ₹18L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Chemical Engineering', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Process Engineering', 'Thermodynamics', 'Fluid Mechanics'], 'employers' => ['Reliance Industries', 'ONGC', 'FMCG Companies']],
            ['title' => 'Civil Engineer/Structural Engineer', 'cat' => 'Engineering', 'domain' => 'Infrastructure', 'short' => 'Plans, designs, and oversees construction and maintenance of building structures.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech in Civil Engineering', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['AutoCAD', 'Structural Analysis', 'Project Management'], 'employers' => ['L&T', 'DLF', 'Tata Projects', 'Government PWD']],
            ['title' => 'Corrosion Engineer', 'cat' => 'Engineering', 'domain' => 'Materials', 'short' => 'Evaluates and mitigates material degradation and corrosion in structures.', 'salary' => '₹5L - ₹14L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech in Metallurgy/Chemical', 'stream' => 'Science (PCM)', 'exams' => ['GATE', 'NACE Certification'], 'skills' => ['Material Science', 'Electrochemistry', 'Inspection'], 'employers' => ['Oil & Gas', 'Marine Industries', 'Manufacturing']],
            ['title' => 'Design Engineer', 'cat' => 'Engineering', 'domain' => 'Mechanical/Core', 'short' => 'Researches and develops ideas for new products and the systems used to make them.', 'salary' => '₹4L - ₹16L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Mechanical/Design', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['SolidWorks', 'CAD', 'Prototyping'], 'employers' => ['Automotive', 'Aerospace', 'Manufacturing']],
            ['title' => 'Development Operations Engineer', 'cat' => 'Engineering', 'domain' => 'Software/IT', 'short' => 'Introduces processes, tools, and methodologies to balance needs throughout the software development life cycle.', 'salary' => '₹8L - ₹25L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech in CS/IT', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main'], 'skills' => ['CI/CD', 'Docker', 'Kubernetes', 'AWS'], 'employers' => ['TCS', 'Infosys', 'Amazon', 'Startups']],
            ['title' => 'Electrical and Electronics Engineer', 'cat' => 'Engineering', 'domain' => 'Electronics', 'short' => 'Designs, develops, tests, and supervises the manufacturing of electrical equipment.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'High', 'qual' => 'B.Tech in EEE', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Circuit Design', 'Power Systems', 'Control Systems'], 'employers' => ['BHEL', 'Siemens', 'ABB', 'Schneider Electric']],
            ['title' => 'Electronics Designer/VLSI/Embedded System Designer', 'cat' => 'Engineering', 'domain' => 'Electronics', 'short' => 'Designs and develops microchips, circuits, and embedded software systems.', 'salary' => '₹6L - ₹22L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech/M.Tech in ECE/VLSI', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Verilog/VHDL', 'C/C++', 'Microcontrollers'], 'employers' => ['Intel', 'Qualcomm', 'Texas Instruments']],
            ['title' => 'Electronics and Communication Engineer', 'cat' => 'Engineering', 'domain' => 'Electronics', 'short' => 'Researches, designs, develops, and tests electronic components and systems.', 'salary' => '₹4L - ₹14L per annum', 'demand' => 'High', 'qual' => 'B.Tech in ECE', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Signal Processing', 'Network Theory', 'Communication Systems'], 'employers' => ['Reliance Jio', 'Airtel', 'Samsung', 'Cisco']],
            ['title' => 'Environmental Engineer', 'cat' => 'Engineering', 'domain' => 'Environment', 'short' => 'Uses principles of engineering, soil science, biology, and chemistry to develop solutions to environmental problems.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Growing', 'qual' => 'B.Tech in Environmental Engineering', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Waste Management', 'EIA', 'Water Treatment'], 'employers' => ['Pollution Control Boards', 'Consultancies', 'NGOs']],
            ['title' => 'Fire and Safety Engineer', 'cat' => 'Engineering', 'domain' => 'Safety', 'short' => 'Designs and implements fire safety codes and systems to prevent accidents.', 'salary' => '₹3L - ₹10L per annum', 'demand' => 'Stable', 'qual' => 'B.Tech in Fire and Safety', 'stream' => 'Science (PCM)', 'exams' => ['State CETs'], 'skills' => ['Risk Assessment', 'Safety Regulations', 'Fire Dynamics'], 'employers' => ['Oil & Gas', 'Construction', 'Manufacturing']],
            ['title' => 'Food Engineer', 'cat' => 'Engineering', 'domain' => 'Food Tech', 'short' => 'Applies engineering principles to food processing, packaging, and preservation.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Food Technology', 'stream' => 'Science (PCM/PCB)', 'exams' => ['JEE Main', 'ICAR AIEEA'], 'skills' => ['Food Processing', 'Quality Assurance', 'Packaging'], 'employers' => ['Nestle', 'ITC', 'Amul', 'Britannia']],
            ['title' => 'Footwear Designer', 'cat' => 'Engineering', 'domain' => 'Design', 'short' => 'Designs and develops footwear products combining aesthetics and ergonomics.', 'salary' => '₹3L - ₹10L per annum', 'demand' => 'Moderate', 'qual' => 'B.Des/Diploma in Footwear Design', 'stream' => 'Any Stream', 'exams' => ['FDDI AIST', 'NIFT'], 'skills' => ['Sketching', 'CAD', 'Material Knowledge'], 'employers' => ['Bata', 'Puma', 'Liberty', 'Export Houses']],
            ['title' => 'Forensic Engineer', 'cat' => 'Engineering', 'domain' => 'Investigation', 'short' => 'Investigates materials, products, structures or components that fail or do not operate or function as intended.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech + Forensic Science Diploma', 'stream' => 'Science (PCM)', 'exams' => ['GATE', 'Forensic Certifications'], 'skills' => ['Failure Analysis', 'Investigation', 'Report Writing'], 'employers' => ['Government Labs', 'Insurance Agencies', 'Consultancies']],
            ['title' => 'Geo-informatics Engineer', 'cat' => 'Engineering', 'domain' => 'GIS', 'short' => 'Works with geographic data, GPS, and satellite imagery to solve spatial problems.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Growing', 'qual' => 'B.Tech in Geoinformatics', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['GIS', 'Remote Sensing', 'Spatial Analysis'], 'employers' => ['ISRO', 'Urban Planning Depts', 'Tech Companies']],
            ['title' => 'Graphics Designer', 'cat' => 'Engineering', 'domain' => 'Design', 'short' => 'Creates visual concepts to communicate ideas that inspire, inform, or captivate consumers.', 'salary' => '₹3L - ₹10L per annum', 'demand' => 'High', 'qual' => 'B.Des/Diploma in Graphics', 'stream' => 'Any Stream', 'exams' => ['NID DAT', 'Portfolio'], 'skills' => ['Adobe Creative Suite', 'Typography', 'UI/UX Basics'], 'employers' => ['Ad Agencies', 'MNCs', 'Media Houses', 'Freelance']],
            ['title' => 'Industrial Designer', 'cat' => 'Engineering', 'domain' => 'Design', 'short' => 'Develops the concepts for manufactured products, such as cars, home appliances, and toys.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'High', 'qual' => 'B.Des in Industrial Design', 'stream' => 'Any Stream', 'exams' => ['NID DAT', 'UCEED'], 'skills' => ['Prototyping', '3D Modeling', 'Ergonomics'], 'employers' => ['Automotive', 'Consumer Goods', 'Design Studios']],
            ['title' => 'Industrial Engineer', 'cat' => 'Engineering', 'domain' => 'Manufacturing', 'short' => 'Optimizes complex processes, systems, or organizations by reducing waste of time, money, materials, etc.', 'salary' => '₹4L - ₹14L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Industrial/Production', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Operations Research', 'Supply Chain', 'Lean Six Sigma'], 'employers' => ['Manufacturing', 'E-commerce', 'Consulting']],
            ['title' => 'Instrumentation Engineer', 'cat' => 'Engineering', 'domain' => 'Electronics', 'short' => 'Designs and manages control systems and instruments used in industrial processes.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'B.Tech in Instrumentation', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['PLC/SCADA', 'Control Systems', 'Sensors'], 'employers' => ['Oil & Gas', 'Power Plants', 'Manufacturing']],
            ['title' => 'Manufacturing Engineer', 'cat' => 'Engineering', 'domain' => 'Manufacturing', 'short' => 'Designs and operates the systems and processes that make products.', 'salary' => '₹4L - ₹14L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Manufacturing/Mechanical', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['CAM', 'Quality Control', 'Lean Manufacturing'], 'employers' => ['Automotive', 'FMCG', 'Electronics']],
            ['title' => 'Marine Engineer', 'cat' => 'Engineering', 'domain' => 'Marine', 'short' => 'Designs, builds, tests, and repairs ships, boats, underwater craft, and offshore platforms.', 'salary' => '₹6L - ₹25L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech in Marine Engineering', 'stream' => 'Science (PCM)', 'exams' => ['IMU CET'], 'skills' => ['Ship Design', 'Propulsion Systems', 'Fluid Mechanics'], 'employers' => ['Shipping Companies', 'Shipyards', 'Indian Navy']],
            ['title' => 'Mechanical Engineer', 'cat' => 'Engineering', 'domain' => 'Mechanical', 'short' => 'Designs, manufactures, and tests mechanical and thermal sensors and devices.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Mechanical Engineering', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Thermodynamics', 'CAD/CAM', 'Mechanics'], 'employers' => ['L&T', 'Tata Motors', 'BHEL', 'PSUs']],
            ['title' => 'Metallurgy Engineer', 'cat' => 'Engineering', 'domain' => 'Materials', 'short' => 'Studies the physical and chemical behavior of metallic elements and their mixtures.', 'salary' => '₹5L - ₹16L per annum', 'demand' => 'Stable', 'qual' => 'B.Tech in Metallurgical Engineering', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Material Science', 'Alloy Design', 'Thermodynamics'], 'employers' => ['Tata Steel', 'JSW', 'SAIL', 'Vedanta']],
            ['title' => 'Mining Engineer', 'cat' => 'Engineering', 'domain' => 'Mining', 'short' => 'Ensures the safe and efficient development of mines and other surface and underground operations.', 'salary' => '₹6L - ₹18L per annum', 'demand' => 'Stable', 'qual' => 'B.Tech in Mining Engineering', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Geology', 'Mine Planning', 'Safety Management'], 'employers' => ['Coal India', 'Vedanta', 'Adani', 'NMDC']],
            ['title' => 'Nanotechnology/Nanoscience Engineer', 'cat' => 'Engineering', 'domain' => 'Materials', 'short' => 'Works on the molecular scale to create new materials and devices.', 'salary' => '₹6L - ₹15L per annum', 'demand' => 'Growing', 'qual' => 'B.Tech/M.Tech in Nanotechnology', 'stream' => 'Science (PCM/PCB)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Material Science', 'Quantum Mechanics', 'Electron Microscopy'], 'employers' => ['Research Labs', 'Semiconductor Industry', 'Pharmaceuticals']],
            ['title' => 'Optical Engineer', 'cat' => 'Engineering', 'domain' => 'Electronics/Physics', 'short' => 'Designs components of optical instruments such as lenses, microscopes, telescopes, and lasers.', 'salary' => '₹5L - ₹14L per annum', 'demand' => 'Stable', 'qual' => 'B.Tech in Optics/Physics', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Optics Design', 'Photonics', 'Laser Tech'], 'employers' => ['ISRO', 'DRDO', 'Telecom', 'Medical Devices']],
            ['title' => 'Petroleum Engineer', 'cat' => 'Engineering', 'domain' => 'Energy', 'short' => 'Designs and develops methods for extracting oil and gas from deposits below the Earth\'s surface.', 'salary' => '₹8L - ₹25L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech in Petroleum Engineering', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Reservoir Engineering', 'Drilling', 'Geophysics'], 'employers' => ['ONGC', 'Reliance', 'Schlumberger', 'Indian Oil']],
            ['title' => 'Pharmaceutical Engineer', 'cat' => 'Engineering', 'domain' => 'Pharma', 'short' => 'Discovers, formulates, and manufactures pharmaceutical products.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'High', 'qual' => 'B.Tech/B.Pharm', 'stream' => 'Science (PCM/PCB)', 'exams' => ['GPAT', 'State CETs'], 'skills' => ['Process Optimization', 'Quality Control', 'Formulation'], 'employers' => ['Sun Pharma', 'Cipla', 'Dr Reddy\'s']],
            ['title' => 'Printing Engineer/Technologist', 'cat' => 'Engineering', 'domain' => 'Manufacturing', 'short' => 'Manages technical aspects of the printing and packaging industry.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Stable', 'qual' => 'B.Tech in Printing Technology', 'stream' => 'Science (PCM)', 'exams' => ['State CETs'], 'skills' => ['Color Theory', 'Pre-press Tech', 'Packaging'], 'employers' => ['Times of India', 'Packaging Firms', 'Publishing Houses']],
            ['title' => 'Process Engineer', 'cat' => 'Engineering', 'domain' => 'Manufacturing', 'short' => 'Designs, operates, controls, and optimizes chemical, physical, and biological processes.', 'salary' => '₹5L - ₹16L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Chemical/Mechanical', 'stream' => 'Science (PCM)', 'exams' => ['GATE', 'JEE Main'], 'skills' => ['Process Design', 'Simulation', 'Quality Assurance'], 'employers' => ['Oil & Gas', 'Pharma', 'FMCG']],
            ['title' => 'Product Designer', 'cat' => 'Engineering', 'domain' => 'Design', 'short' => 'Combines art, science, and technology to create new products.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'High', 'qual' => 'B.Des/B.Tech', 'stream' => 'Any Stream', 'exams' => ['UCEED', 'NID DAT'], 'skills' => ['UI/UX', 'Prototyping', 'User Research'], 'employers' => ['Tech Startups', 'Consumer Electronics', 'Software Cos']],
            ['title' => 'Quality Assurance Engineer', 'cat' => 'Engineering', 'domain' => 'Software/Manufacturing', 'short' => 'Ensures products meet certain thresholds of acceptability.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech', 'stream' => 'Science (PCM)', 'exams' => ['ISTQB (optional)', 'JEE Main'], 'skills' => ['Testing', 'Automation', 'Six Sigma'], 'employers' => ['TCS', 'Infosys', 'Manufacturing Plants']],
            ['title' => 'Railway Engineer', 'cat' => 'Engineering', 'domain' => 'Infrastructure', 'short' => 'Deals with the design, construction and operation of all types of railway systems.', 'salary' => '₹6L - ₹18L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Civil/Mechanical/Electrical', 'stream' => 'Science (PCM)', 'exams' => ['IES', 'GATE', 'RRB'], 'skills' => ['Transportation Engg', 'Structural Design', 'Signalling'], 'employers' => ['Indian Railways', 'Metro Corporations', 'L&T']],
            ['title' => 'Robotics Engineer', 'cat' => 'Engineering', 'domain' => 'Mechatronics', 'short' => 'Designs and creates robots and robotic systems to perform duties that humans cannot or prefer not to.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech in Robotics/Mechatronics', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['AI/ML', 'Kinematics', 'Control Systems'], 'employers' => ['GreyOrange', 'Boston Dynamics', 'Automotive']],
            ['title' => 'Sales Engineer', 'cat' => 'Engineering', 'domain' => 'Sales', 'short' => 'Uses technical skills to explain the benefits of products or services to potential customers.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'High', 'qual' => 'B.Tech + MBA (Optional)', 'stream' => 'Science (PCM)', 'exams' => ['CAT/MAT (for MBA)'], 'skills' => ['B2B Sales', 'Technical Knowledge', 'Communication'], 'employers' => ['Siemens', 'Cisco', 'IBM', 'Schneider Electric']],
            ['title' => 'Smart Manufacturing and Automation Engineer', 'cat' => 'Engineering', 'domain' => 'Mechatronics', 'short' => 'Implements Industry 4.0 concepts to automate and optimize manufacturing.', 'salary' => '₹5L - ₹18L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Automation/Mechatronics', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['PLC/SCADA', 'IoT', 'Robotics'], 'employers' => ['Industry 4.0 Firms', 'Automotive', 'FMCG']],
            ['title' => 'Sound Engineer', 'cat' => 'Engineering', 'domain' => 'Media', 'short' => 'Operates, maintains, and sets up equipment for recording, mixing, and reproducing sounds.', 'salary' => '₹3L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'Diploma/B.Sc in Sound Engineering', 'stream' => 'Any Stream (Science preferred)', 'exams' => ['FTII', 'Skill Certification'], 'skills' => ['Audio Mixing', 'Pro Tools', 'Acoustics'], 'employers' => ['Film Studios', 'TV Channels', 'Music Labels']],
            ['title' => 'Textile Engineer', 'cat' => 'Engineering', 'domain' => 'Manufacturing', 'short' => 'Deals with the application of scientific and engineering principles to the design and control of all aspects of fiber, textile, and apparel processes.', 'salary' => '₹3.5L - ₹10L per annum', 'demand' => 'Stable', 'qual' => 'B.Tech in Textile Technology', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'State CETs'], 'skills' => ['Fabric Analysis', 'Yarn Manufacturing', 'Quality Control'], 'employers' => ['Raymond', 'Arvind Mills', 'Vardhman']],
            ['title' => 'Tool Engineer', 'cat' => 'Engineering', 'domain' => 'Mechanical', 'short' => 'Designs tools, jigs, fixtures, and dies for mass production.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech in Mechanical/Tool Engineering', 'stream' => 'Science (PCM)', 'exams' => ['NTTF', 'JEE Main'], 'skills' => ['CAD/CAM', 'CNC Programming', 'Material Science'], 'employers' => ['Automotive', 'Aerospace', 'Manufacturing']],
            ['title' => 'Water Resource Engineer', 'cat' => 'Engineering', 'domain' => 'Civil/Environment', 'short' => 'Designs new systems and equipment that help manage human water resources.', 'salary' => '₹4L - ₹14L per annum', 'demand' => 'Growing', 'qual' => 'B.Tech in Civil/Environmental', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Hydraulics', 'AutoCAD', 'Environmental EIA'], 'employers' => ['Government Water Boards', 'L&T', 'Consultancies']],

            // ==================================================
            // CATEGORY: Government Services / Competitive Exams
            // ==================================================
            ['title' => 'Agniveer', 'cat' => 'Government', 'domain' => 'Defence', 'short' => 'Soldiers recruited below the rank of commissioned officers in Indian Armed Forces under the Agnipath scheme.', 'salary' => '₹4.76L - ₹6.92L per annum', 'demand' => 'High', 'qual' => '10th / 12th Pass', 'stream' => 'Any Stream', 'exams' => ['Indian Army/Navy/Air Force Agniveer Rally'], 'skills' => ['Physical Fitness', 'Discipline', 'Teamwork'], 'employers' => ['Indian Army', 'Indian Navy', 'Indian Air Force']],
            ['title' => 'Border Security Force', 'cat' => 'Government', 'domain' => 'Paramilitary', 'short' => 'Guards India\'s land border during peacetime and prevents transnational crime.', 'salary' => '₹3.5L - ₹10L per annum', 'demand' => 'High', 'qual' => '10th/12th/Graduation (depends on rank)', 'stream' => 'Any Stream', 'exams' => ['SSC GD', 'UPSC CAPF'], 'skills' => ['Physical Fitness', 'Combat', 'Surveillance'], 'employers' => ['Ministry of Home Affairs']],
            ['title' => 'CISF Officer', 'cat' => 'Government', 'domain' => 'Paramilitary', 'short' => 'Provides security to industrial units, airports, and vital installations.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC CAPF', 'SSC CPO'], 'skills' => ['Security Management', 'Leadership', 'Crisis Response'], 'employers' => ['Ministry of Home Affairs']],
            ['title' => 'Coast Guard', 'cat' => 'Government', 'domain' => 'Defence', 'short' => 'Protects India\'s maritime interests and enforces maritime law.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'Moderate', 'qual' => '12th (PCM) / Graduation', 'stream' => 'Science (PCM) preferred', 'exams' => ['Indian Coast Guard Navik/Yantrik/Asst Commandant'], 'skills' => ['Navigation', 'Maritime Law', 'Search and Rescue'], 'employers' => ['Ministry of Defence']],
            ['title' => 'CRPF Officer', 'cat' => 'Government', 'domain' => 'Paramilitary', 'short' => 'Maintains internal security and tackles insurgency.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC CAPF', 'SSC CPO'], 'skills' => ['Tactical Operations', 'Crowd Control', 'Leadership'], 'employers' => ['Ministry of Home Affairs']],
            ['title' => 'Customs Officer', 'cat' => 'Government', 'domain' => 'Revenue', 'short' => 'Checks baggage, cargo, and mail for illegal items and collects duties.', 'salary' => '₹6L - ₹15L per annum', 'demand' => 'High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['SSC CGL', 'UPSC Civil Services'], 'skills' => ['Law Enforcement', 'Investigation', 'Attention to Detail'], 'employers' => ['CBIC', 'Ministry of Finance']],
            ['title' => 'FSSAI Officer', 'cat' => 'Government', 'domain' => 'Regulatory', 'short' => 'Ensures food safety and standards across the country.', 'salary' => '₹5L - ₹12L per annum', 'demand' => 'Moderate', 'qual' => 'Degree in Food Tech/Agriculture/Science', 'stream' => 'Science', 'exams' => ['FSSAI Recruitment Exam'], 'skills' => ['Food Safety Laws', 'Inspection', 'Quality Analysis'], 'employers' => ['FSSAI', 'State Food Departments']],
            ['title' => 'Gramin Dak Sevak', 'cat' => 'Government', 'domain' => 'Postal', 'short' => 'Manages branch post offices in rural areas.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => '10th Pass with Math and English', 'stream' => 'Any Stream', 'exams' => ['Merit-based on 10th marks'], 'skills' => ['Basic Computer', 'Local Language', 'Record Keeping'], 'employers' => ['India Post']],
            ['title' => 'Indian Administrative Service', 'cat' => 'Government', 'domain' => 'Administration', 'short' => 'Manages government affairs and frames policies at district, state, and central levels.', 'salary' => '₹7L - ₹30L per annum', 'demand' => 'Very High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC Civil Services Exam (CSE)'], 'skills' => ['Public Administration', 'Leadership', 'Policy Making'], 'employers' => ['Government of India', 'State Governments']],
            ['title' => 'Indian Air Force Officer', 'cat' => 'Government', 'domain' => 'Defence', 'short' => 'Leads and manages operations in the flying, technical, or ground duty branches.', 'salary' => '₹8L - ₹25L per annum', 'demand' => 'High', 'qual' => '12th (PCM) / Graduation / B.Tech', 'stream' => 'Science (PCM) preferred', 'exams' => ['NDA', 'AFCAT', 'CDSE'], 'skills' => ['Aviation', 'Leadership', 'Strategic Planning'], 'employers' => ['Indian Air Force']],
            ['title' => 'Indian Army Officer', 'cat' => 'Government', 'domain' => 'Defence', 'short' => 'Commands troops and manages national security operations on land.', 'salary' => '₹8L - ₹25L per annum', 'demand' => 'High', 'qual' => '12th / Graduation', 'stream' => 'Any Stream', 'exams' => ['NDA', 'CDSE', 'SSC Tech'], 'skills' => ['Combat Tactics', 'Leadership', 'Physical Endurance'], 'employers' => ['Indian Army']],
            ['title' => 'Indian Foreign Service', 'cat' => 'Government', 'domain' => 'Diplomacy', 'short' => 'Represents India internationally and manages foreign relations.', 'salary' => '₹8L - ₹30L+ per annum (plus allowances)', 'demand' => 'Very High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC Civil Services Exam (CSE)'], 'skills' => ['Diplomacy', 'International Relations', 'Negotiation'], 'employers' => ['Ministry of External Affairs']],
            ['title' => 'Indian Forest Service', 'cat' => 'Government', 'domain' => 'Environment', 'short' => 'Manages the environment, forests, and wildlife of the country.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'High', 'qual' => 'Graduation in Science/Engineering/Agriculture', 'stream' => 'Science', 'exams' => ['UPSC IFoS Exam'], 'skills' => ['Conservation', 'Forestry', 'Administration'], 'employers' => ['Ministry of Environment, Forest and Climate Change']],
            ['title' => 'Indian Home Guard', 'cat' => 'Government', 'domain' => 'Paramilitary', 'short' => 'A voluntary force assisting police in maintaining internal security.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'Stable', 'qual' => '10th / 12th Pass', 'stream' => 'Any Stream', 'exams' => ['State Police/Home Guard Recruitment'], 'skills' => ['Discipline', 'Basic Law Enforcement', 'Crowd Control'], 'employers' => ['State Governments']],
            ['title' => 'Indian Navy Officer', 'cat' => 'Government', 'domain' => 'Defence', 'short' => 'Commands naval vessels, submarines, and aircraft to protect maritime borders.', 'salary' => '₹8L - ₹25L per annum', 'demand' => 'High', 'qual' => '12th (PCM) / B.Tech', 'stream' => 'Science (PCM)', 'exams' => ['NDA', 'CDSE', 'INET'], 'skills' => ['Navigation', 'Naval Tactics', 'Leadership'], 'employers' => ['Indian Navy']],
            ['title' => 'Indian Police Service', 'cat' => 'Government', 'domain' => 'Law Enforcement', 'short' => 'Maintains law and order, prevents crime, and manages police forces.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'Very High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC Civil Services Exam (CSE)'], 'skills' => ['Law Enforcement', 'Crisis Management', 'Investigation'], 'employers' => ['State Police Departments', 'Central Agencies']],
            ['title' => 'Indian Railway Accounts Service', 'cat' => 'Government', 'domain' => 'Railways', 'short' => 'Manages the finances and accounts of Indian Railways.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC Civil Services Exam (CSE)'], 'skills' => ['Accounting', 'Financial Management', 'Auditing'], 'employers' => ['Indian Railways']],
            ['title' => 'Indian Railway Personnel Service', 'cat' => 'Government', 'domain' => 'Railways', 'short' => 'Manages human resources and personnel administration for Indian Railways.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC Civil Services Exam (CSE)'], 'skills' => ['HR Management', 'Administration', 'Labor Laws'], 'employers' => ['Indian Railways']],
            ['title' => 'Indian Railway Service of Electrical Engineers', 'cat' => 'Government', 'domain' => 'Railways', 'short' => 'Manages electrical assets and power supply systems of Indian Railways.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Electrical Engineering', 'stream' => 'Science (PCM)', 'exams' => ['UPSC Engineering Services Exam (IES)'], 'skills' => ['Electrical Systems', 'Project Management', 'Maintenance'], 'employers' => ['Indian Railways']],
            ['title' => 'Indian Railway Service of Engineers', 'cat' => 'Government', 'domain' => 'Railways', 'short' => 'Maintains and develops civil engineering infrastructure of Indian Railways.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Civil Engineering', 'stream' => 'Science (PCM)', 'exams' => ['UPSC Engineering Services Exam (IES)'], 'skills' => ['Civil Engineering', 'Track Maintenance', 'Structural Design'], 'employers' => ['Indian Railways']],
            ['title' => 'Indian Railway Service of Mechanical Engineers', 'cat' => 'Government', 'domain' => 'Railways', 'short' => 'Manages rolling stock, locomotives, and production units of Indian Railways.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Mechanical Engineering', 'stream' => 'Science (PCM)', 'exams' => ['UPSC Engineering Services Exam (IES)'], 'skills' => ['Mechanical Systems', 'Locomotive Maintenance', 'Production Engg'], 'employers' => ['Indian Railways']],
            ['title' => 'Indian Railway Service of Signal Engineers', 'cat' => 'Government', 'domain' => 'Railways', 'short' => 'Manages signaling and telecommunication networks of Indian Railways.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'High', 'qual' => 'B.Tech in Electronics/Telecommunication', 'stream' => 'Science (PCM)', 'exams' => ['UPSC Engineering Services Exam (IES)'], 'skills' => ['Telecommunications', 'Signaling Systems', 'Electronics'], 'employers' => ['Indian Railways']],
            ['title' => 'Indian Railway Stores Service', 'cat' => 'Government', 'domain' => 'Railways', 'short' => 'Manages procurement and supply chain for Indian Railways.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'High', 'qual' => 'B.Tech (Any Branch)', 'stream' => 'Science (PCM)', 'exams' => ['UPSC Engineering Services Exam (IES)'], 'skills' => ['Supply Chain Management', 'Procurement', 'Inventory Control'], 'employers' => ['Indian Railways']],
            ['title' => 'Indian Railways Traffic Service', 'cat' => 'Government', 'domain' => 'Railways', 'short' => 'Manages passenger and freight train operations and commercial activities.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC Civil Services Exam (CSE)'], 'skills' => ['Operations Management', 'Logistics', 'Administration'], 'employers' => ['Indian Railways']],
            ['title' => 'Indian Revenue Service', 'cat' => 'Government', 'domain' => 'Taxation', 'short' => 'Administers direct and indirect taxes for the Government of India.', 'salary' => '₹7L - ₹25L per annum', 'demand' => 'Very High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC Civil Services Exam (CSE)'], 'skills' => ['Taxation Law', 'Auditing', 'Administration'], 'employers' => ['CBDT', 'CBIC']],
            ['title' => 'Inspector of Income Tax', 'cat' => 'Government', 'domain' => 'Taxation', 'short' => 'Assists in assessment, collection, and investigation of income tax matters.', 'salary' => '₹6L - ₹12L per annum', 'demand' => 'High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['SSC CGL'], 'skills' => ['Tax Assessment', 'Investigation', 'Data Analysis'], 'employers' => ['Income Tax Department']],
            ['title' => 'ITBP Officer', 'cat' => 'Government', 'domain' => 'Paramilitary', 'short' => 'Guards the Indo-Tibetan border and conducts high-altitude rescue operations.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC CAPF'], 'skills' => ['High-Altitude Survival', 'Combat', 'Border Security'], 'employers' => ['Ministry of Home Affairs']],
            ['title' => 'Loco Pilot', 'cat' => 'Government', 'domain' => 'Railways', 'short' => 'Drives and operates passenger and freight trains.', 'salary' => '₹4L - ₹10L per annum', 'demand' => 'High', 'qual' => 'ITI / Diploma in Engineering', 'stream' => 'Science/Tech', 'exams' => ['RRB ALP'], 'skills' => ['Train Operation', 'Safety Regulations', 'Technical Troubleshooting'], 'employers' => ['Indian Railways']],
            ['title' => 'Merchant Navy', 'cat' => 'Government', 'domain' => 'Maritime', 'short' => 'Operates commercial ships transporting cargo and passengers internationally.', 'salary' => '₹6L - ₹36L per annum', 'demand' => 'Moderate', 'qual' => '12th (PCM) / B.Sc Nautical Science', 'stream' => 'Science (PCM)', 'exams' => ['IMU CET'], 'skills' => ['Navigation', 'Seamanship', 'Marine Engineering'], 'employers' => ['Shipping Corporations', 'Maersk', 'MSC']],
            ['title' => 'Police Constable', 'cat' => 'Government', 'domain' => 'Law Enforcement', 'short' => 'Performs basic policing duties, patrolling, and assisting in investigations.', 'salary' => '₹2.5L - ₹5L per annum', 'demand' => 'Very High', 'qual' => '12th Pass', 'stream' => 'Any Stream', 'exams' => ['State Police Constable Exams'], 'skills' => ['Physical Fitness', 'Community Policing', 'Basic Law'], 'employers' => ['State Police Departments']],
            ['title' => 'Railway Protection Force', 'cat' => 'Government', 'domain' => 'Railways', 'short' => 'Protects railway passengers, property, and passenger areas.', 'salary' => '₹3.5L - ₹8L per annum', 'demand' => 'High', 'qual' => '10th / Graduation (for Sub-Inspector)', 'stream' => 'Any Stream', 'exams' => ['RRB RPF Exam'], 'skills' => ['Security Operations', 'Law Enforcement', 'Physical Fitness'], 'employers' => ['Indian Railways']],
            ['title' => 'Sashastra Seema Bal Officer', 'cat' => 'Government', 'domain' => 'Paramilitary', 'short' => 'Guards the Indo-Nepal and Indo-Bhutan borders.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Moderate', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['UPSC CAPF'], 'skills' => ['Border Security', 'Intelligence Gathering', 'Combat'], 'employers' => ['Ministry of Home Affairs']],
            ['title' => 'Sub-inspector of Police', 'cat' => 'Government', 'domain' => 'Law Enforcement', 'short' => 'Investigates crimes, files chargesheets, and maintains law and order.', 'salary' => '₹4L - ₹8L per annum', 'demand' => 'High', 'qual' => 'Graduation', 'stream' => 'Any Stream', 'exams' => ['SSC CPO', 'State SI Exams'], 'skills' => ['Investigation', 'Criminal Law', 'Leadership'], 'employers' => ['State Police Departments', 'Delhi Police']],

            // ==================================================
            // CATEGORY: Information Technology / Modern Tech & AI
            // ==================================================
            ['title' => 'Artificial Intelligence Engineer', 'cat' => 'IT', 'domain' => 'AI/ML', 'short' => 'Builds AI models and algorithms using machine learning and deep learning.', 'salary' => '₹8L - ₹30L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech/M.Tech in CS/AI', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Python', 'TensorFlow', 'Neural Networks'], 'employers' => ['Google', 'Microsoft', 'OpenAI', 'TCS']],
            ['title' => 'Augmented Reality Engineer', 'cat' => 'IT', 'domain' => 'AR/VR', 'short' => 'Develops software for augmented reality applications and glasses.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'Growing', 'qual' => 'B.Tech in CS/IT', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main'], 'skills' => ['Unity3D', 'C#', 'ARKit/ARCore'], 'employers' => ['Meta', 'Apple', 'Gaming Studios']],
            ['title' => 'Big Data Analyst', 'cat' => 'IT', 'domain' => 'Data Science', 'short' => 'Analyzes massive amounts of data to uncover hidden patterns and market trends.', 'salary' => '₹6L - ₹22L per annum', 'demand' => 'High', 'qual' => 'B.Tech / B.Sc in Math/Stats/CS', 'stream' => 'Science/Commerce with Math', 'exams' => ['CUET', 'JEE Main'], 'skills' => ['Hadoop', 'Spark', 'SQL', 'Python'], 'employers' => ['Amazon', 'Mu Sigma', 'Accenture']],
            ['title' => 'Blockchain Developer', 'cat' => 'IT', 'domain' => 'Web3', 'short' => 'Develops decentralized applications (dApps) and smart contracts.', 'salary' => '₹8L - ₹25L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech in CS/IT', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main'], 'skills' => ['Solidity', 'Ethereum', 'Cryptography'], 'employers' => ['Polygon', 'WazirX', 'Web3 Startups']],
            ['title' => 'Cloud Engineer', 'cat' => 'IT', 'domain' => 'Cloud Computing', 'short' => 'Designs, implements, and manages cloud infrastructure.', 'salary' => '₹6L - ₹25L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech in CS/IT', 'stream' => 'Science (PCM)', 'exams' => ['AWS/Azure Certifications'], 'skills' => ['AWS/Azure', 'Linux', 'Networking'], 'employers' => ['Amazon', 'Microsoft', 'TCS', 'Wipro']],
            ['title' => 'Computer Hardware Engineer', 'cat' => 'IT', 'domain' => 'Hardware', 'short' => 'Researches, designs, develops, and tests computer systems and components.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'Stable', 'qual' => 'B.Tech in Computer Engineering/ECE', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Circuit Design', 'Microprocessors', 'Testing'], 'employers' => ['Intel', 'AMD', 'Dell', 'HP']],
            ['title' => 'Computer Network Architect', 'cat' => 'IT', 'domain' => 'Networking', 'short' => 'Designs and builds data communication networks, including LANs and WANs.', 'salary' => '₹8L - ₹24L per annum', 'demand' => 'High', 'qual' => 'B.Tech in IT/CS + CCNA/CCNP', 'stream' => 'Science (PCM)', 'exams' => ['Cisco Certifications'], 'skills' => ['Network Design', 'Cybersecurity', 'Routing/Switching'], 'employers' => ['Cisco', 'Airtel', 'Tech Mahindra']],
            ['title' => 'Computer Science Engineer', 'cat' => 'IT', 'domain' => 'Software', 'short' => 'Applies computer science theory and software development fundamentals.', 'salary' => '₹4L - ₹20L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech in Computer Science', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Algorithms', 'Data Structures', 'Programming'], 'employers' => ['FAANG', 'TCS', 'Infosys']],
            ['title' => 'Computer Scientist', 'cat' => 'IT', 'domain' => 'Research', 'short' => 'Conducts research to solve complex computing problems and invent new tech.', 'salary' => '₹10L - ₹35L per annum', 'demand' => 'Growing', 'qual' => 'Ph.D. / M.Tech in CS', 'stream' => 'Science (PCM)', 'exams' => ['GATE', 'GRE'], 'skills' => ['Research', 'Advanced Algorithms', 'Math'], 'employers' => ['Google Research', 'Microsoft Research', 'IISc']],
            ['title' => 'Cyber Security Specialist', 'cat' => 'IT', 'domain' => 'Security', 'short' => 'Protects systems, networks, and programs from digital attacks.', 'salary' => '₹6L - ₹25L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech in CS/IT/Cyber Security', 'stream' => 'Science (PCM)', 'exams' => ['CEH', 'CISSP', 'JEE Main'], 'skills' => ['Ethical Hacking', 'Network Security', 'Cryptography'], 'employers' => ['Banks', 'Government Agencies', 'IT Consultancies']],
            ['title' => 'Data Scientist', 'cat' => 'IT', 'domain' => 'Data Science', 'short' => 'Extracts meaning from and interprets data, requiring tools and methods from stats and ML.', 'salary' => '₹8L - ₹25L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech / Masters in Data Science/Stats', 'stream' => 'Science/Commerce with Math', 'exams' => ['GATE', 'JAM'], 'skills' => ['Python', 'Machine Learning', 'Statistics'], 'employers' => ['Mu Sigma', 'Fractal Analytics', 'FAANG']],
            ['title' => 'Database Administrator', 'cat' => 'IT', 'domain' => 'Database', 'short' => 'Uses specialized software to store and organize data, ensuring its security and availability.', 'salary' => '₹5L - ₹16L per annum', 'demand' => 'High', 'qual' => 'B.Tech / BCA / MCA', 'stream' => 'Any Stream with Math/Computers', 'exams' => ['Oracle Certifications'], 'skills' => ['SQL', 'Oracle/MySQL', 'Database Tuning'], 'employers' => ['Banks', 'IT Services', 'E-commerce']],
            ['title' => 'Full Stack Developer', 'cat' => 'IT', 'domain' => 'Software', 'short' => 'Develops both client-side and server-side software.', 'salary' => '₹6L - ₹25L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech in CS/IT or Bootcamp', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main'], 'skills' => ['MERN/MEAN Stack', 'JavaScript', 'APIs'], 'employers' => ['Startups', 'Product Companies', 'IT Services']],
            ['title' => 'Game Designer and Developer', 'cat' => 'IT', 'domain' => 'Gaming', 'short' => 'Creates video games, from conceptualizing gameplay to writing code.', 'salary' => '₹4L - ₹18L per annum', 'demand' => 'Growing', 'qual' => 'B.Tech/B.Sc in Game Design/CS', 'stream' => 'Any Stream (Science preferred)', 'exams' => ['Portfolio', 'Institute Specific Exams'], 'skills' => ['Unity/Unreal Engine', 'C#/C++', 'Game Mechanics'], 'employers' => ['Ubisoft', 'EA Games', 'Mobile Gaming Startups']],
            ['title' => 'Help Desk Analyst', 'cat' => 'IT', 'domain' => 'Support', 'short' => 'Provides technical support and troubleshooting for software and hardware issues.', 'salary' => '₹2.5L - ₹6L per annum', 'demand' => 'High', 'qual' => 'BCA / B.Sc / Diploma', 'stream' => 'Any Stream', 'exams' => ['CompTIA A+'], 'skills' => ['Troubleshooting', 'Communication', 'OS Knowledge'], 'employers' => ['BPOs', 'IT Services', 'Corporate IT Depts']],
            ['title' => 'Information Technology Engineer', 'cat' => 'IT', 'domain' => 'Software/Infrastructure', 'short' => 'Maintains computer infrastructures and develops software solutions.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'High', 'qual' => 'B.Tech in IT', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'GATE'], 'skills' => ['Networking', 'Programming', 'Systems Administration'], 'employers' => ['TCS', 'Wipro', 'HCL', 'Infosys']],
            ['title' => 'Internet of Things Solutions Architect', 'cat' => 'IT', 'domain' => 'IoT', 'short' => 'Designs the architecture for IoT networks connecting devices to the cloud.', 'salary' => '₹10L - ₹30L per annum', 'demand' => 'Growing', 'qual' => 'B.Tech in CS/ECE', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main'], 'skills' => ['IoT Protocols', 'Cloud Computing', 'System Architecture'], 'employers' => ['Bosch', 'Samsung', 'Siemens']],
            ['title' => 'Network Administrator', 'cat' => 'IT', 'domain' => 'Networking', 'short' => 'Maintains computing environment by identifying network requirements and installing upgrades.', 'salary' => '₹3.5L - ₹10L per annum', 'demand' => 'High', 'qual' => 'B.Tech / BCA / Hardware Diploma', 'stream' => 'Any Stream', 'exams' => ['CCNA'], 'skills' => ['LAN/WAN', 'Firewalls', 'Troubleshooting'], 'employers' => ['ISPs', 'Corporate IT Depts', 'Data Centers']],
            ['title' => 'Programmer/Coder/Software Engineer', 'cat' => 'IT', 'domain' => 'Software', 'short' => 'Writes, tests, and maintains the detailed instructions that computers must follow.', 'salary' => '₹4L - ₹20L per annum', 'demand' => 'Very High', 'qual' => 'B.Tech / MCA / BCA', 'stream' => 'Science (PCM) preferred', 'exams' => ['JEE Main', 'NIMCET'], 'skills' => ['Java/Python/C++', 'DSA', 'Version Control'], 'employers' => ['Tech Companies', 'Banks', 'Startups']],
            ['title' => 'SEO Manager', 'cat' => 'IT', 'domain' => 'Digital Marketing', 'short' => 'Improves website rankings on search engines to increase organic traffic.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'High', 'qual' => 'Any Graduation', 'stream' => 'Any Stream', 'exams' => ['Digital Marketing Certifications'], 'skills' => ['SEO Tools', 'Analytics', 'Content Strategy'], 'employers' => ['Marketing Agencies', 'E-commerce', 'Media Houses']],
            ['title' => 'Software Application Packager', 'cat' => 'IT', 'domain' => 'Software/Support', 'short' => 'Prepares software applications for mass deployment across enterprise networks.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech / BCA', 'stream' => 'Any Stream with Computers', 'exams' => ['Certification'], 'skills' => ['MSI', 'App-V', 'Scripting'], 'employers' => ['IT Consultancies', 'MNCs']],
            ['title' => 'Systems Analyst', 'cat' => 'IT', 'domain' => 'IT Management', 'short' => 'Examines current IT systems and designs solutions to help organizations operate more efficiently.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'High', 'qual' => 'B.Tech / MBA in IT', 'stream' => 'Science (PCM)', 'exams' => ['CAT', 'JEE Main'], 'skills' => ['Systems Design', 'Business Analysis', 'SQL'], 'employers' => ['Deloitte', 'Accenture', 'TCS']],
            ['title' => 'User Experience Designer', 'cat' => 'IT', 'domain' => 'Design', 'short' => 'Enhances user satisfaction by improving usability, accessibility, and pleasure in interaction.', 'salary' => '₹5L - ₹18L per annum', 'demand' => 'High', 'qual' => 'B.Des / B.Tech / Any Degree + UX Cert', 'stream' => 'Any Stream', 'exams' => ['NID DAT', 'Portfolio'], 'skills' => ['Figma', 'Wireframing', 'User Research'], 'employers' => ['Product Companies', 'Design Agencies', 'Startups']],
            ['title' => 'Virtual Reality Engineer', 'cat' => 'IT', 'domain' => 'AR/VR', 'short' => 'Builds immersive 3D environments and applications.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'Growing', 'qual' => 'B.Tech in CS/IT', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main'], 'skills' => ['Unreal Engine', 'Unity', '3D Math'], 'employers' => ['Gaming Studios', 'Tech Giants', 'EdTech']],
            ['title' => 'Web Analyst', 'cat' => 'IT', 'domain' => 'Digital Marketing', 'short' => 'Analyzes website traffic and user behavior to improve website performance.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'High', 'qual' => 'B.Tech / B.Sc / BBA', 'stream' => 'Any Stream', 'exams' => ['Google Analytics Cert'], 'skills' => ['Google Analytics', 'Data Visualization', 'A/B Testing'], 'employers' => ['E-commerce', 'Media Agencies', 'Tech Startups']],
            ['title' => 'Web Designer', 'cat' => 'IT', 'domain' => 'Design', 'short' => 'Creates the visual layout and user interface of websites.', 'salary' => '₹3L - ₹10L per annum', 'demand' => 'High', 'qual' => 'Diploma / Degree in Design/CS', 'stream' => 'Any Stream', 'exams' => ['Portfolio'], 'skills' => ['HTML/CSS', 'UI Design', 'Responsive Design'], 'employers' => ['IT Agencies', 'Freelance', 'Corporate IT']],
            
            // ==================================================
            // CATEGORY: Management / Business & Management
            // ==================================================
            ['title' => 'Assistant Catering Manager', 'cat' => 'Management', 'domain' => 'Hospitality', 'short' => 'Assists in planning and managing food service operations at events or institutions.', 'salary' => '₹2.5L - ₹6L per annum', 'demand' => 'Stable', 'qual' => 'Degree/Diploma in Hotel Management', 'stream' => 'Any Stream', 'exams' => ['NCHMCT JEE'], 'skills' => ['Food Service Management', 'Team Leading', 'Budgeting'], 'employers' => ['Hotels', 'Event Management Cos', 'Corporate Cafeterias']],
            ['title' => 'BPO Executive', 'cat' => 'Management', 'domain' => 'Operations', 'short' => 'Handles customer queries and business processes for external client companies.', 'salary' => '₹2L - ₹5L per annum', 'demand' => 'Very High', 'qual' => '12th Pass / Graduation', 'stream' => 'Any Stream', 'exams' => ['Company Interviews'], 'skills' => ['Communication', 'Customer Service', 'Basic Computer'], 'employers' => ['Genpact', 'TCS BPO', 'Concentrix']],
            ['title' => 'Event Manager', 'cat' => 'Management', 'domain' => 'Events', 'short' => 'Plans, organizes, and executes events like weddings, conferences, and festivals.', 'salary' => '₹3L - ₹12L per annum', 'demand' => 'High', 'qual' => 'BBA / Diploma in Event Management', 'stream' => 'Any Stream', 'exams' => ['Institute Level Exams'], 'skills' => ['Organization', 'Vendor Management', 'Crisis Management'], 'employers' => ['Wizcraft', 'TCI', 'Freelance']],
            ['title' => 'Human Resource Manager', 'cat' => 'Management', 'domain' => 'HR', 'short' => 'Oversees recruiting, interviewing, and hiring of new staff; consults on strategic planning.', 'salary' => '₹5L - ₹20L per annum', 'demand' => 'High', 'qual' => 'MBA in HR', 'stream' => 'Any Stream', 'exams' => ['CAT', 'XAT', 'MAT'], 'skills' => ['Recruitment', 'Employee Relations', 'Labor Laws'], 'employers' => ['All Corporate Sectors', 'IT Companies', 'Manufacturing']],
            ['title' => 'Inventory Manager', 'cat' => 'Management', 'domain' => 'Supply Chain', 'short' => 'Tracks, manages, and organizes stock levels, deliveries, and supplies.', 'salary' => '₹4L - ₹10L per annum', 'demand' => 'High', 'qual' => 'BBA / B.Com / MBA in Supply Chain', 'stream' => 'Commerce / Any Stream', 'exams' => ['CAT (for MBA)'], 'skills' => ['Inventory Control', 'ERP Software', 'Logistics'], 'employers' => ['Amazon', 'Flipkart', 'Retail Chains']],
            ['title' => 'Knowledge Process Outsourcing Executive', 'cat' => 'Management', 'domain' => 'Operations', 'short' => 'Handles complex, information-related business activities outsourced by client companies.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'High', 'qual' => 'Graduation/Post-Graduation in relevant field', 'stream' => 'Any Stream', 'exams' => ['Company Interviews'], 'skills' => ['Data Analysis', 'Domain Expertise', 'Research'], 'employers' => ['Evalueserve', 'WNS', 'Genpact']],
            ['title' => 'Purchasing and Materials Manager', 'cat' => 'Management', 'domain' => 'Supply Chain', 'short' => 'Buys products for organizations to use or resell, evaluating suppliers and negotiating contracts.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'High', 'qual' => 'B.Tech + MBA / BBA', 'stream' => 'Any Stream', 'exams' => ['CAT', 'MAT'], 'skills' => ['Negotiation', 'Vendor Management', 'Procurement'], 'employers' => ['Manufacturing', 'Retail', 'Construction']],
            ['title' => 'Retail Manager', 'cat' => 'Management', 'domain' => 'Retail', 'short' => 'Oversees the daily operations of a retail store or department.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'High', 'qual' => 'BBA / MBA in Retail Management', 'stream' => 'Any Stream', 'exams' => ['Institute Level Exams'], 'skills' => ['Store Operations', 'Sales Strategy', 'Customer Service'], 'employers' => ['Reliance Retail', 'Shoppers Stop', 'Lifestyle']],
            ['title' => 'Rural Development Specialist/Manager', 'cat' => 'Management', 'domain' => 'Social/Agri', 'short' => 'Implements programs aimed at improving the standard of living in rural areas.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Moderate', 'qual' => 'MBA in Rural Management / MSW', 'stream' => 'Any Stream', 'exams' => ['IRMA', 'TISSNET (CUET PG)'], 'skills' => ['Project Management', 'Community Outreach', 'Policy Implementation'], 'employers' => ['NGOs', 'NABARD', 'Government Schemes']],
            ['title' => 'Sales and Marketing Manager', 'cat' => 'Management', 'domain' => 'Marketing', 'short' => 'Directs sales teams and develops marketing campaigns to promote products.', 'salary' => '₹6L - ₹25L per annum', 'demand' => 'Very High', 'qual' => 'MBA in Sales & Marketing', 'stream' => 'Any Stream', 'exams' => ['CAT', 'XAT', 'SNAP'], 'skills' => ['Marketing Strategy', 'B2B/B2C Sales', 'Leadership'], 'employers' => ['FMCG', 'Tech Companies', 'Banking']],
            ['title' => 'Sports Agent/Manager', 'cat' => 'Management', 'domain' => 'Sports', 'short' => 'Manages the careers of athletes, negotiates contracts, and handles public relations.', 'salary' => '₹5L - ₹20L+ per annum', 'demand' => 'Growing', 'qual' => 'MBA in Sports Management / Law Degree', 'stream' => 'Any Stream', 'exams' => ['Institute Specific Exams'], 'skills' => ['Negotiation', 'PR', 'Sports Law Knowledge'], 'employers' => ['Sports Management Firms', 'Franchises (IPL, PKL)']],
            ['title' => 'Sports Equipment Manager', 'cat' => 'Management', 'domain' => 'Sports', 'short' => 'Maintains, orders, and organizes athletic equipment for teams and organizations.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Stable', 'qual' => 'Graduation / Diploma in Sports Management', 'stream' => 'Any Stream', 'exams' => ['Institute Interviews'], 'skills' => ['Inventory Management', 'Organization', 'Logistics'], 'employers' => ['Sports Academies', 'Professional Teams']],
        ];

        // Process insertion
        foreach ($careers as $c) {
            $field = current(array_filter($fields, fn($f) => $f && str_starts_with($f->name, explode('/', $c['cat'])[0]))); // Wait, let's use the explicit mapping array.
            $fieldModel = $fields[$c['cat']] ?? null;
            
            if (!$fieldModel) continue;

            $slug = Str::slug($c['title']);
            $imageName = $slug . '.svg';
            
            // Format roadmap as JSON array
            $roadmap = [
                "Complete 10+2 with " . $c['stream'],
                "Qualify entrance exams like " . implode(", ", $c['exams']),
                "Pursue " . $c['qual'],
                "Gain skills in " . implode(", ", $c['skills']),
                "Apply for jobs in " . implode(", ", array_slice($c['employers'], 0, 2))
            ];

            Career::firstOrCreate(
                ['slug' => $slug],
                [
                    'name' => $c['title'],
                    'field_id' => $fieldModel->id,
                    'sub_domain' => $c['domain'],
                    'description' => $c['short'],
                    'qualification' => $c['qual'],
                    'stream' => $c['stream'],
                    'salary_range' => $c['salary'],
                    'demand_level' => $c['demand'] ?? 'High',
                    'roadmap' => $roadmap,
                    'icon' => 'fa-briefcase',
                    'skills' => $c['skills'],
                    'entrance_exams' => $c['exams'],
                    'job_opportunities' => $c['employers'],
                    'image' => $imageName
                ]
            );
        }
    }
}
