<?php

namespace Database\Seeders;

use App\Models\Career;
use App\Models\Field;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MassCareersExpansionSeeder3 extends Seeder
{
    public function run(): void
    {
        $fields = [
            'Science' => Field::where('slug', 'science')->first(),
            'Trades' => Field::where('slug', 'skill-trades-manufacturing-retail')->first(),
        ];

        $careers = [
            // ==================================================
            // CATEGORY: Research & Development
            // ==================================================
            ['title' => 'Anthropologist', 'cat' => 'Science', 'domain' => 'Social Science', 'short' => 'Studies human societies, cultures, and their development.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'MA/M.Sc in Anthropology', 'stream' => 'Arts/Science', 'exams' => ['UGC NET'], 'skills' => ['Research', 'Cultural Analysis', 'Fieldwork'], 'employers' => ['Archaeological Survey of India', 'Universities', 'NGOs']],
            ['title' => 'Archaeologist', 'cat' => 'Science', 'domain' => 'History/Science', 'short' => 'Studies human history and prehistory through the excavation of sites and analysis of artifacts.', 'salary' => '₹3L - ₹10L per annum', 'demand' => 'Stable', 'qual' => 'MA in Archaeology', 'stream' => 'Arts/Humanities', 'exams' => ['UGC NET'], 'skills' => ['Excavation', 'Historical Knowledge', 'Analysis'], 'employers' => ['ASI', 'Museums', 'Universities']],
            ['title' => 'Astrophysicist', 'cat' => 'Science', 'domain' => 'Physics', 'short' => 'Applies the laws of physics and chemistry to explain the birth, life and death of stars, planets, galaxies.', 'salary' => '₹6L - ₹18L per annum', 'demand' => 'Stable', 'qual' => 'M.Sc/Ph.D in Astrophysics/Physics', 'stream' => 'Science (PCM)', 'exams' => ['GATE', 'JEST'], 'skills' => ['Math', 'Data Analysis', 'Observational Astronomy'], 'employers' => ['ISRO', 'IUCAA', 'TIFR']],
            ['title' => 'Botanist', 'cat' => 'Science', 'domain' => 'Biology', 'short' => 'Studies plant life, including their physiology, structure, genetics, ecology, etc.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'M.Sc in Botany', 'stream' => 'Science (PCB)', 'exams' => ['CSIR NET', 'CUET PG'], 'skills' => ['Plant Taxonomy', 'Research', 'Ecology'], 'employers' => ['Botanical Survey of India', 'Agri-Tech Cos', 'Universities']],
            ['title' => 'Child Development Specialist', 'cat' => 'Science', 'domain' => 'Psychology', 'short' => 'Focuses on the physical, emotional, and psychological development of children.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Growing', 'qual' => 'MA/M.Sc in Child Psychology/Human Development', 'stream' => 'Arts/Science', 'exams' => ['CUET PG'], 'skills' => ['Child Psychology', 'Counseling', 'Observation'], 'employers' => ['Schools', 'Hospitals', 'NGOs']],
            ['title' => 'Criminologist', 'cat' => 'Science', 'domain' => 'Social Science', 'short' => 'Studies the causes, consequences, and prevention of criminal behavior.', 'salary' => '₹4L - ₹10L per annum', 'demand' => 'Moderate', 'qual' => 'MA in Criminology', 'stream' => 'Arts/Science', 'exams' => ['UGC NET'], 'skills' => ['Criminal Psychology', 'Research', 'Data Analysis'], 'employers' => ['Police Departments', 'Research Institutes', 'NGOs']],
            ['title' => 'Curator', 'cat' => 'Science', 'domain' => 'History/Arts', 'short' => 'Manages collections of artworks, artifacts, and historical items at museums.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'MA in Museology/History/Art History', 'stream' => 'Arts/Humanities', 'exams' => ['Institute Level Exams'], 'skills' => ['Preservation', 'Exhibition Design', 'Research'], 'employers' => ['National Museums', 'Art Galleries', 'Heritage Sites']],
            ['title' => 'Cytologist/Cytotechnologist', 'cat' => 'Science', 'domain' => 'Medical Science', 'short' => 'Studies cells to detect abnormalities, such as cancer.', 'salary' => '₹3.5L - ₹9L per annum', 'demand' => 'Stable', 'qual' => 'M.Sc in Cytology/Life Sciences', 'stream' => 'Science (PCB)', 'exams' => ['University Exams'], 'skills' => ['Microscopy', 'Cellular Analysis', 'Lab Techniques'], 'employers' => ['Diagnostic Labs', 'Hospitals', 'Cancer Research Centers']],
            ['title' => 'Data Collector or Field Survey Enumerator', 'cat' => 'Science', 'domain' => 'Research', 'short' => 'Collects data directly from the field for various research studies or census.', 'salary' => '₹1.5L - ₹3.5L per annum', 'demand' => 'Stable', 'qual' => '12th Pass / Graduation', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Communication', 'Data Entry', 'Local Language'], 'employers' => ['NSSO', 'Market Research Firms', 'NGOs']],
            ['title' => 'Demographer', 'cat' => 'Science', 'domain' => 'Social Science', 'short' => 'Studies human populations, their size, composition, and distribution.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'Moderate', 'qual' => 'MA/M.Sc in Population Studies/Demography', 'stream' => 'Arts/Science', 'exams' => ['IIPS Entrance'], 'skills' => ['Statistical Analysis', 'Research', 'Data Interpretation'], 'employers' => ['UN Agencies', 'Government Depts', 'Think Tanks']],
            ['title' => 'Ecologist', 'cat' => 'Science', 'domain' => 'Environment', 'short' => 'Studies the relationship between organisms and their environments.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Growing', 'qual' => 'M.Sc in Ecology/Environmental Science', 'stream' => 'Science (PCB)', 'exams' => ['CSIR NET'], 'skills' => ['Fieldwork', 'Environmental Impact Assessment', 'Data Analysis'], 'employers' => ['Wildlife Institute of India', 'NGOs', 'Consultancies']],
            ['title' => 'Economist', 'cat' => 'Science', 'domain' => 'Economics', 'short' => 'Studies the production and distribution of resources, goods, and services.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'High', 'qual' => 'MA in Economics', 'stream' => 'Commerce/Arts/Science with Math', 'exams' => ['Indian Economic Service (IES)', 'CUET PG'], 'skills' => ['Econometrics', 'Data Analysis', 'Policy Formulation'], 'employers' => ['RBI', 'Government Ministries', 'Banks']],
            ['title' => 'Engineering Physicist', 'cat' => 'Science', 'domain' => 'Physics/Engineering', 'short' => 'Applies physics principles to solve engineering and technological problems.', 'salary' => '₹6L - ₹18L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech in Engineering Physics', 'stream' => 'Science (PCM)', 'exams' => ['JEE Main', 'JEE Advanced'], 'skills' => ['Applied Physics', 'Math', 'Problem Solving'], 'employers' => ['ISRO', 'DRDO', 'Tech Companies']],
            ['title' => 'English Literature Scholar', 'cat' => 'Science', 'domain' => 'Humanities', 'short' => 'Researches and studies classic and modern English literary works.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'MA/Ph.D in English Literature', 'stream' => 'Arts/Humanities', 'exams' => ['UGC NET'], 'skills' => ['Critical Thinking', 'Writing', 'Research'], 'employers' => ['Universities', 'Publishing Houses', 'Media']],
            ['title' => 'Epigraphist', 'cat' => 'Science', 'domain' => 'History', 'short' => 'Studies ancient inscriptions and writings.', 'salary' => '₹4L - ₹10L per annum', 'demand' => 'Stable', 'qual' => 'MA in History/Epigraphy', 'stream' => 'Arts/Humanities', 'exams' => ['UGC NET'], 'skills' => ['Ancient Languages', 'Historical Analysis', 'Research'], 'employers' => ['ASI', 'Universities', 'Museums']],
            ['title' => 'Forensic Scientist', 'cat' => 'Science', 'domain' => 'Science/Law', 'short' => 'Applies scientific methods to investigate crimes and analyze evidence.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Moderate', 'qual' => 'M.Sc in Forensic Science', 'stream' => 'Science', 'exams' => ['Institute Entrance Exams'], 'skills' => ['Lab Techniques', 'Evidence Analysis', 'Attention to Detail'], 'employers' => ['State/Central Forensic Labs', 'CBI', 'Private Detective Agencies']],
            ['title' => 'Genetic Engineer', 'cat' => 'Science', 'domain' => 'Biotechnology', 'short' => 'Manipulates the genetic makeup of an organism using biotechnology.', 'salary' => '₹5L - ₹18L per annum', 'demand' => 'Growing', 'qual' => 'M.Sc/B.Tech in Genetics/Biotech', 'stream' => 'Science (PCB/PCM)', 'exams' => ['GATE', 'CSIR NET'], 'skills' => ['Molecular Biology', 'Gene Editing (CRISPR)', 'Research'], 'employers' => ['Pharma Cos', 'Agri-Tech', 'Research Institutes']],
            ['title' => 'Geographer', 'cat' => 'Science', 'domain' => 'Earth Science', 'short' => 'Studies the Earth, its features, and the distribution of life on it.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'MA/M.Sc in Geography', 'stream' => 'Arts/Science', 'exams' => ['UGC NET'], 'skills' => ['GIS', 'Spatial Analysis', 'Fieldwork'], 'employers' => ['Survey of India', 'Urban Planning Depts', 'Universities']],
            ['title' => 'Geologist', 'cat' => 'Science', 'domain' => 'Earth Science', 'short' => 'Studies the materials, processes, products, physical nature, and history of the Earth.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'Moderate', 'qual' => 'M.Sc/M.Tech in Applied Geology', 'stream' => 'Science', 'exams' => ['UPSC Geoscientist Exam', 'GATE'], 'skills' => ['Rock Analysis', 'Mapping', 'Fieldwork'], 'employers' => ['GSI', 'ONGC', 'Mining Companies']],
            ['title' => 'Historian', 'cat' => 'Science', 'domain' => 'History', 'short' => 'Researches, analyzes, and interprets the past.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'MA/Ph.D in History', 'stream' => 'Arts/Humanities', 'exams' => ['UGC NET'], 'skills' => ['Research', 'Archival Work', 'Writing'], 'employers' => ['Universities', 'ICHR', 'Museums']],
            ['title' => 'Mathematician', 'cat' => 'Science', 'domain' => 'Math', 'short' => 'Conducts research in fundamental mathematics or applies mathematical techniques to solve problems.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'Stable', 'qual' => 'M.Sc/Ph.D in Mathematics', 'stream' => 'Science/Commerce with Math', 'exams' => ['CSIR NET', 'NBHM'], 'skills' => ['Advanced Math', 'Logic', 'Problem Solving'], 'employers' => ['TIFR', 'ISI', 'Tech/Finance Firms']],
            ['title' => 'Meteorologist', 'cat' => 'Science', 'domain' => 'Earth Science', 'short' => 'Studies the atmosphere to forecast the weather and understand climate patterns.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'Stable', 'qual' => 'M.Sc/M.Tech in Atmospheric Science/Meteorology', 'stream' => 'Science (PCM)', 'exams' => ['GATE', 'CSIR NET'], 'skills' => ['Data Analysis', 'Weather Modeling', 'Physics'], 'employers' => ['IMD', 'ISRO', 'Aviation Sector']],
            ['title' => 'Museologist', 'cat' => 'Science', 'domain' => 'History/Arts', 'short' => 'Studies museums, their history, role in society, and manages their organization.', 'salary' => '₹3.5L - ₹10L per annum', 'demand' => 'Stable', 'qual' => 'MA in Museology', 'stream' => 'Arts/Humanities', 'exams' => ['Institute Specific Exams'], 'skills' => ['Conservation', 'Curation', 'History'], 'employers' => ['National Museums', 'Heritage Foundations', 'Art Galleries']],
            ['title' => 'Nanoscientist', 'cat' => 'Science', 'domain' => 'Materials', 'short' => 'Studies and manipulates matter on an atomic and molecular scale.', 'salary' => '₹6L - ₹18L per annum', 'demand' => 'Growing', 'qual' => 'M.Sc/M.Tech/Ph.D in Nanoscience', 'stream' => 'Science', 'exams' => ['GATE', 'CSIR NET'], 'skills' => ['Material Science', 'Quantum Physics', 'Lab Tech'], 'employers' => ['Research Institutes', 'Semiconductor Cos', 'Pharma']],
            ['title' => 'Paleontologist', 'cat' => 'Science', 'domain' => 'Earth Science', 'short' => 'Studies fossils to understand the history of life on Earth.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'M.Sc/Ph.D in Geology/Paleontology', 'stream' => 'Science', 'exams' => ['CSIR NET', 'GATE'], 'skills' => ['Fossil Analysis', 'Geology', 'Biology'], 'employers' => ['GSI', 'Universities', 'Museums']],
            ['title' => 'Physicist', 'cat' => 'Science', 'domain' => 'Physics', 'short' => 'Studies the fundamental properties of matter and energy.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'Stable', 'qual' => 'M.Sc/Ph.D in Physics', 'stream' => 'Science (PCM)', 'exams' => ['CSIR NET', 'JEST'], 'skills' => ['Advanced Math', 'Experimentation', 'Data Analysis'], 'employers' => ['BARC', 'ISRO', 'TIFR', 'Universities']],
            ['title' => 'Political Scientist', 'cat' => 'Science', 'domain' => 'Social Science', 'short' => 'Studies the origin, development, and operation of political systems.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'Moderate', 'qual' => 'MA/Ph.D in Political Science', 'stream' => 'Arts/Humanities', 'exams' => ['UGC NET'], 'skills' => ['Policy Analysis', 'Research', 'Writing'], 'employers' => ['Think Tanks', 'Media', 'Universities']],
            ['title' => 'Scientific Assistant', 'cat' => 'Science', 'domain' => 'Research', 'short' => 'Assists scientists in conducting experiments and analyzing results.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Stable', 'qual' => 'B.Sc / M.Sc in relevant field', 'stream' => 'Science', 'exams' => ['SSC Scientific Assistant Exam'], 'skills' => ['Lab Techniques', 'Data Entry', 'Equipment Handling'], 'employers' => ['IMD', 'DRDO Labs', 'ICAR']],
            ['title' => 'Seismologist', 'cat' => 'Science', 'domain' => 'Earth Science', 'short' => 'Studies earthquakes and seismic waves that move through and around the Earth.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'Stable', 'qual' => 'M.Sc/M.Tech in Geophysics/Seismology', 'stream' => 'Science', 'exams' => ['GATE', 'UPSC Geoscientist'], 'skills' => ['Data Analysis', 'Geophysics', 'Math'], 'employers' => ['National Center for Seismology', 'ONGC', 'Research Labs']],
            ['title' => 'Sociologist', 'cat' => 'Science', 'domain' => 'Social Science', 'short' => 'Studies human society, social behavior, and social interactions.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'MA/Ph.D in Sociology', 'stream' => 'Arts/Humanities', 'exams' => ['UGC NET'], 'skills' => ['Qualitative Research', 'Data Analysis', 'Writing'], 'employers' => ['NGOs', 'Government Planning Depts', 'Universities']],
            ['title' => 'Space Scientist', 'cat' => 'Science', 'domain' => 'Physics/Astronomy', 'short' => 'Studies space exploration, planetary science, and cosmology.', 'salary' => '₹6L - ₹20L per annum', 'demand' => 'Stable', 'qual' => 'M.Sc/Ph.D in Space Science/Physics', 'stream' => 'Science (PCM)', 'exams' => ['JEST', 'GATE'], 'skills' => ['Astrophysics', 'Data Analysis', 'Math'], 'employers' => ['ISRO', 'PRL', 'IIST']],
            ['title' => 'Statistician', 'cat' => 'Science', 'domain' => 'Math/Stats', 'short' => 'Develops and applies mathematical or statistical theory to collect, organize, and interpret data.', 'salary' => '₹6L - ₹18L per annum', 'demand' => 'High', 'qual' => 'M.Sc/M.Stat in Statistics', 'stream' => 'Science/Commerce with Math', 'exams' => ['Indian Statistical Service (ISS)', 'ISI Entrance'], 'skills' => ['Statistical Modeling', 'R/Python', 'Data Analysis'], 'employers' => ['CSO', 'NSSO', 'Finance/Tech Firms']],
            ['title' => 'Toxicologist', 'cat' => 'Science', 'domain' => 'Medical/Biology', 'short' => 'Studies the toxic effects of chemicals and physical agents on living organisms.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Moderate', 'qual' => 'M.Sc in Toxicology/Life Sciences', 'stream' => 'Science (PCB)', 'exams' => ['University Exams'], 'skills' => ['Lab Analysis', 'Chemistry', 'Biology'], 'employers' => ['Pharma Cos', 'Forensic Labs', 'Pollution Control Boards']],
            ['title' => 'Virologist', 'cat' => 'Science', 'domain' => 'Medical/Biology', 'short' => 'Studies viruses and virus-like agents, including their structure and behavior.', 'salary' => '₹5L - ₹15L per annum', 'demand' => 'Growing', 'qual' => 'M.Sc/Ph.D in Virology/Microbiology', 'stream' => 'Science (PCB)', 'exams' => ['CSIR NET', 'ICMR JRF'], 'skills' => ['Microbiology', 'Lab Techniques', 'Research'], 'employers' => ['NIV', 'ICMR', 'Vaccine Manufacturers']],
            ['title' => 'Zoologist', 'cat' => 'Science', 'domain' => 'Biology', 'short' => 'Studies animals and their behavior, physiology, classification, and distribution.', 'salary' => '₹4L - ₹12L per annum', 'demand' => 'Stable', 'qual' => 'M.Sc in Zoology', 'stream' => 'Science (PCB)', 'exams' => ['CSIR NET', 'CUET PG'], 'skills' => ['Animal Biology', 'Fieldwork', 'Research'], 'employers' => ['Zoological Survey of India', 'Wildlife NGOs', 'Universities']],

            // ==================================================
            // CATEGORY: Technical & Skill Trades
            // ==================================================
            ['title' => 'Appliqué Artisan', 'cat' => 'Trades', 'domain' => 'Handicraft', 'short' => 'Creates decorative designs by sewing pieces of fabric onto a larger piece.', 'salary' => '₹1.5L - ₹3.5L per annum', 'demand' => 'Stable', 'qual' => 'Skill Certification/Experience', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Sewing', 'Design', 'Patience'], 'employers' => ['Handicraft Export Firms', 'Boutiques', 'Self-Employed']],
            ['title' => 'Assistant Beauty Therapist', 'cat' => 'Trades', 'domain' => 'Beauty/Wellness', 'short' => 'Provides basic skin care, makeup, and hair removal treatments under supervision.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => 'Certification in Beauty Therapy', 'stream' => 'Any Stream', 'exams' => ['NSDC Certification'], 'skills' => ['Skincare', 'Communication', 'Hygiene'], 'employers' => ['Salons', 'Spas', 'Beauty Clinics']],
            ['title' => 'Assistant Carpenter (Wooden Furniture)', 'cat' => 'Trades', 'domain' => 'Construction/Manufacturing', 'short' => 'Assists head carpenters in cutting, shaping, and installing building materials.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => 'ITI / Practical Experience', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Woodworking', 'Measuring', 'Tool Handling'], 'employers' => ['Furniture Manufacturers', 'Construction Sites', 'Contractors']],
            ['title' => 'Assistant False Ceiling and Drywall Installer', 'cat' => 'Trades', 'domain' => 'Construction', 'short' => 'Assists in measuring, cutting, and installing drywall and false ceilings.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => 'Practical Training', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Measurement', 'Tool Use', 'Physical Stamina'], 'employers' => ['Interior Decorators', 'Construction Contractors']],
            ['title' => 'Assistant Fitter (Levelling, Alignment and Balancing)', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Assists in the precise assembly and alignment of mechanical components.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'Stable', 'qual' => 'ITI Fitter (Optional)', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Precision', 'Tool Handling', 'Mechanical Aptitude'], 'employers' => ['Manufacturing Plants', 'Workshops']],
            ['title' => 'Assistant Hair Stylist', 'cat' => 'Trades', 'domain' => 'Beauty/Wellness', 'short' => 'Assists senior stylists with washing, basic cutting, and styling hair.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => 'Hair Styling Course', 'stream' => 'Any Stream', 'exams' => ['Skill Certification'], 'skills' => ['Haircare', 'Customer Service', 'Basic Styling'], 'employers' => ['Salons', 'Freelance']],
            ['title' => 'Assistant Surveyor', 'cat' => 'Trades', 'domain' => 'Construction', 'short' => 'Assists land surveyors in measuring boundaries and topography.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'Moderate', 'qual' => 'ITI Surveyor / Diploma in Civil', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['Measurement Tools', 'Math', 'Fieldwork'], 'employers' => ['Construction Firms', 'Government PWD']],
            ['title' => 'Auto Service Technician', 'cat' => 'Trades', 'domain' => 'Automotive', 'short' => 'Inspects, maintains, and repairs cars and light trucks.', 'salary' => '₹2L - ₹5L per annum', 'demand' => 'High', 'qual' => 'ITI Motor Mechanic', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Diagnostics', 'Repairing', 'Tool Usage'], 'employers' => ['Authorized Service Centers', 'Independent Garages']],
            ['title' => 'Auto/E-Rickshaw Driver and Technician', 'cat' => 'Trades', 'domain' => 'Transport', 'short' => 'Operates and performs basic maintenance on auto-rickshaws or e-rickshaws.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'High', 'qual' => 'Valid Driving License', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Driving', 'Basic Maintenance', 'Customer Interaction'], 'employers' => ['Self-Employed', 'Fleet Operators']],
            ['title' => 'Automotive Electrician', 'cat' => 'Trades', 'domain' => 'Automotive', 'short' => 'Installs, maintains, and repairs electrical wiring and computer-based equipment in vehicles.', 'salary' => '₹2L - ₹5L per annum', 'demand' => 'High', 'qual' => 'ITI Electrician/Auto Electrical', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Wiring', 'Diagnostics', 'Electrical Repair'], 'employers' => ['Service Centers', 'Automotive Factories']],
            ['title' => 'Bamboo Mat Weaver', 'cat' => 'Trades', 'domain' => 'Handicraft', 'short' => 'Weaves bamboo strips to create mats, baskets, and other products.', 'salary' => '₹1.2L - ₹2.5L per annum', 'demand' => 'Stable', 'qual' => 'Practical Skill', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Weaving', 'Manual Dexterity', 'Design'], 'employers' => ['Handicraft Cooperatives', 'Self-Employed']],
            ['title' => 'Bamboo Utility Product Tailor', 'cat' => 'Trades', 'domain' => 'Handicraft', 'short' => 'Creates utility products like bags and folders using bamboo fabric/mats.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'Stable', 'qual' => 'Skill Training', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Tailoring', 'Material Handling', 'Design'], 'employers' => ['Eco-friendly Product Brands', 'Self-Employed']],
            ['title' => 'Cake Artist', 'cat' => 'Trades', 'domain' => 'Food Trades', 'short' => 'Bakes and decorates custom cakes for special occasions.', 'salary' => '₹2L - ₹6L per annum', 'demand' => 'High', 'qual' => 'Baking Course / Diploma in Bakery', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Baking', 'Icing/Fondant Work', 'Creativity'], 'employers' => ['Bakeries', 'Hotels', 'Self-Employed (Home Baker)']],
            ['title' => 'Camp Helper', 'cat' => 'Trades', 'domain' => 'Tourism', 'short' => 'Assists in setting up and managing outdoor camps for tourists.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'Stable', 'qual' => 'Physical Fitness', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Tent Pitching', 'Basic Cooking', 'Outdoor Survival'], 'employers' => ['Trekking Agencies', 'Adventure Camps']],
            ['title' => 'CCTV Installation Technician', 'cat' => 'Trades', 'domain' => 'Electronics', 'short' => 'Installs, maintains, and repairs closed-circuit television security systems.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'Very High', 'qual' => 'ITI Electronics / Short-term Course', 'stream' => 'Any Stream', 'exams' => ['Skill Certification'], 'skills' => ['Wiring', 'Networking Basics', 'Tool Usage'], 'employers' => ['Security Agencies', 'Tech Service Cos', 'Self-Employed']],
            ['title' => 'Chef', 'cat' => 'Trades', 'domain' => 'Food Trades', 'short' => 'A trained professional cook who is proficient in all aspects of food preparation.', 'salary' => '₹3L - ₹15L per annum', 'demand' => 'High', 'qual' => 'Degree/Diploma in Culinary Arts', 'stream' => 'Any Stream', 'exams' => ['Institute Entrance'], 'skills' => ['Cooking Tech', 'Menu Planning', 'Kitchen Management'], 'employers' => ['Hotels', 'Restaurants', 'Cruise Ships']],
            ['title' => 'Child Caretaker (Non-clinical)', 'cat' => 'Trades', 'domain' => 'Personal Care', 'short' => 'Provides care and supervision for children in daycares or private homes.', 'salary' => '₹1.5L - ₹3.5L per annum', 'demand' => 'High', 'qual' => 'Nanny/Childcare Certification', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Childcare', 'Patience', 'Basic First Aid'], 'employers' => ['Daycare Centers', 'Private Households']],
            ['title' => 'Chocolatier', 'cat' => 'Trades', 'domain' => 'Food Trades', 'short' => 'Specializes in making confectionery from chocolate.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Moderate', 'qual' => 'Culinary/Baking Diploma', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Chocolate Tempering', 'Flavor Pairing', 'Creativity'], 'employers' => ['Luxury Hotels', 'Artisan Chocolate Brands', 'Self-Employed']],
            ['title' => 'CNC Operator (Turning)', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Operates computer numerical control machines to cut and shape metal or plastic.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'High', 'qual' => 'ITI Machinist/Turner', 'stream' => 'Science/Tech', 'exams' => ['Skill Test'], 'skills' => ['CNC Programming Basic', 'Precision Measurement', 'Machine Operation'], 'employers' => ['Manufacturing Plants', 'Auto Parts Makers']],
            ['title' => 'Coffee Taster/Barista/Q Grader', 'cat' => 'Trades', 'domain' => 'Food Trades', 'short' => 'Prepares coffee, evaluates its quality, and creates coffee blends.', 'salary' => '₹2.5L - ₹6L per annum', 'demand' => 'Growing', 'qual' => 'Barista Certification', 'stream' => 'Any Stream', 'exams' => ['SCA Certification (for Q Grader)'], 'skills' => ['Espresso Pulling', 'Latte Art', 'Sensory Evaluation'], 'employers' => ['Coffee Chains (Starbucks, Third Wave)', 'Roasteries']],
            ['title' => 'Construction-Painter and Decorator', 'cat' => 'Trades', 'domain' => 'Construction', 'short' => 'Applies paint, wallpaper, and other finishes to interior and exterior surfaces.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'High', 'qual' => 'Practical Experience', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Painting Tech', 'Surface Prep', 'Color Mixing'], 'employers' => ['Contractors', 'Interior Designers', 'Self-Employed']],
            ['title' => 'Crochet Lace Maker – Furnishings', 'cat' => 'Trades', 'domain' => 'Handicraft', 'short' => 'Creates intricate lace patterns using a crochet hook for home furnishings.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'Stable', 'qual' => 'Skill Training', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Crochet', 'Pattern Reading', 'Patience'], 'employers' => ['Textile Export Firms', 'Boutiques', 'Self-Employed']],
            ['title' => 'Doors and Windows Fixer', 'cat' => 'Trades', 'domain' => 'Construction', 'short' => 'Specializes in the installation of doors, windows, and their frames.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'High', 'qual' => 'ITI Carpenter / Experience', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Measurement', 'Installation', 'Tool Usage'], 'employers' => ['Construction Cos', 'Hardware Retailers']],
            ['title' => 'Draughtsman', 'cat' => 'Trades', 'domain' => 'Engineering Support', 'short' => 'Prepares technical drawings and plans based on engineer\'s or architect\'s rough sketches.', 'salary' => '₹2.5L - ₹5L per annum', 'demand' => 'High', 'qual' => 'ITI Draughtsman (Civil/Mech)', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['AutoCAD', 'Technical Drawing', 'Attention to Detail'], 'employers' => ['Architectural Firms', 'Manufacturing', 'Construction']],
            ['title' => 'DTH Set Top Box Installation and Service Technician', 'cat' => 'Trades', 'domain' => 'Electronics Support', 'short' => 'Installs Direct-to-Home satellite dishes and repairs set-top boxes.', 'salary' => '₹1.8L - ₹3.5L per annum', 'demand' => 'Stable', 'qual' => 'ITI/Short-term Course', 'stream' => 'Any Stream', 'exams' => ['Skill Certification'], 'skills' => ['Signal Alignment', 'Wiring', 'Customer Service'], 'employers' => ['Tata Play', 'Airtel DTH', 'Local Dealers']],
            ['title' => 'Electric Vehicle Assembly Technician', 'cat' => 'Trades', 'domain' => 'Automotive', 'short' => 'Assembles components of electric vehicles in a manufacturing plant.', 'salary' => '₹2.5L - ₹4.5L per annum', 'demand' => 'Growing', 'qual' => 'ITI Electrician/Fitter', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['Assembly Line Work', 'Electrical Basics', 'Safety'], 'employers' => ['Ola Electric', 'Ather', 'Tata Motors']],
            ['title' => 'Electrician (General)', 'cat' => 'Trades', 'domain' => 'Construction/Maintenance', 'short' => 'Installs, maintains, and repairs electrical wiring and equipment.', 'salary' => '₹2L - ₹5L per annum', 'demand' => 'Very High', 'qual' => 'ITI Electrician', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['Wiring', 'Diagnostics', 'Safety Protocols'], 'employers' => ['Construction', 'Facility Management', 'Self-Employed']],
            ['title' => 'E-waste Collector', 'cat' => 'Trades', 'domain' => 'Waste Management', 'short' => 'Collects and sorts electronic waste for recycling and safe disposal.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'Growing', 'qual' => 'Basic Training', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Sorting', 'Material Knowledge', 'Safety'], 'employers' => ['E-Waste Recycling Firms', 'NGOs']],
            ['title' => 'Field Technician- Other Home Appliances', 'cat' => 'Trades', 'domain' => 'Electronics Support', 'short' => 'Installs and repairs home appliances like washing machines and microwaves.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'High', 'qual' => 'ITI / Short-term Course', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Appliance Repair', 'Customer Service', 'Troubleshooting'], 'employers' => ['Samsung', 'LG', 'Urban Company']],
            ['title' => 'Fitter (Electrical and Electronic Assembly)', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Assembles electrical and electronic components and sub-assemblies.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'High', 'qual' => 'ITI Fitter/Electrician', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['Soldering', 'Blueprint Reading', 'Tool Usage'], 'employers' => ['Electronics Manufacturing', 'Auto Components']],
            ['title' => 'Fitter (Fabrication)', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Cuts, shapes, and joins metal parts using welding and cutting tools.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'High', 'qual' => 'ITI Fitter/Welder', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['Welding', 'Metal Cutting', 'Measurement'], 'employers' => ['Heavy Engineering', 'Construction', 'Shipyards']],
            ['title' => 'Fitter (Mechanical Assembly)', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Fits and assembles metal parts and sub-assemblies to fabricate machines.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'High', 'qual' => 'ITI Fitter', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['Assembly', 'Tool Use', 'Blueprint Reading'], 'employers' => ['Automotive Factories', 'Machine Tools Cos']],
            ['title' => 'Fitter (Processing)', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Maintains and repairs equipment in process industries like chemicals or food.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'Stable', 'qual' => 'ITI Fitter', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['Maintenance', 'Troubleshooting', 'Safety'], 'employers' => ['Chemical Plants', 'FMCG Factories']],
            ['title' => 'Food and Beverage Service Steward', 'cat' => 'Trades', 'domain' => 'Hospitality', 'short' => 'Serves food and beverages to guests in hotels, restaurants, or banquets.', 'salary' => '₹1.8L - ₹3.5L per annum', 'demand' => 'High', 'qual' => '10th/12th Pass / Short-term Course', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Customer Service', 'Etiquette', 'Physical Stamina'], 'employers' => ['Hotels', 'Restaurants', 'Catering Cos']],
            ['title' => 'General Housekeeper', 'cat' => 'Trades', 'domain' => 'Hospitality/Facility Management', 'short' => 'Maintains cleanliness and tidiness in hotels, offices, or private homes.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => '8th/10th Pass', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Cleaning Tech', 'Time Management', 'Reliability'], 'employers' => ['Hotels', 'Facility Management Cos', 'Hospitals']],
            ['title' => 'Helper (Carpenter)', 'cat' => 'Trades', 'domain' => 'Construction', 'short' => 'Assists carpenters by holding materials, handing tools, and cleaning the work area.', 'salary' => '₹1.5L - ₹2.5L per annum', 'demand' => 'Stable', 'qual' => 'None', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Physical Labor', 'Listening', 'Basic Tool Knowledge'], 'employers' => ['Contractors', 'Carpentry Shops']],
            ['title' => 'Helper-Fabrication', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Assists fabricators and welders by preparing materials and moving heavy items.', 'salary' => '₹1.5L - ₹2.5L per annum', 'demand' => 'High', 'qual' => 'None', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Physical Strength', 'Safety Awareness', 'Material Handling'], 'employers' => ['Fabrication Workshops', 'Construction']],
            ['title' => 'Home Delivery Boy', 'cat' => 'Trades', 'domain' => 'Logistics/Gig', 'short' => 'Delivers food, groceries, or packages to customers\' doorsteps.', 'salary' => '₹1.8L - ₹4L per annum', 'demand' => 'Very High', 'qual' => '10th Pass + Two Wheeler License', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Driving', 'Navigation', 'Time Management'], 'employers' => ['Zomato', 'Swiggy', 'Amazon', 'Zepto']],
            ['title' => 'Home Cook', 'cat' => 'Trades', 'domain' => 'Food Trades', 'short' => 'Cooks meals for families in private households or runs a small tiffin service.', 'salary' => '₹1.5L - ₹3.5L per annum', 'demand' => 'High', 'qual' => 'Cooking Skill', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Cooking', 'Hygiene', 'Time Management'], 'employers' => ['Private Households', 'Self-Employed (Tiffin)'] ],
            ['title' => 'Housekeeping Attendant (Manual Cleaning)', 'cat' => 'Trades', 'domain' => 'Facility Management', 'short' => 'Cleans offices, malls, or public areas using manual tools and chemicals.', 'salary' => '₹1.5L - ₹2.5L per annum', 'demand' => 'High', 'qual' => '8th/10th Pass', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Cleaning', 'Physical Stamina', 'Discipline'], 'employers' => ['Facility Management Firms', 'Malls']],
            ['title' => 'Industrial Production Worker (Food Processing)', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Works on the assembly line to process, package, and inspect food products.', 'salary' => '₹1.8L - ₹3L per annum', 'demand' => 'High', 'qual' => '10th/12th Pass', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Machine Operation', 'Hygiene Standards', 'Speed'], 'employers' => ['FMCG Factories (Britannia, Parle)']],
            ['title' => 'Installer – Frameless Glass Doors/Windows', 'cat' => 'Trades', 'domain' => 'Construction', 'short' => 'Specializes in cutting, fitting, and installing frameless glass structures.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'Moderate', 'qual' => 'Practical Training', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Glass Handling', 'Precision Measuring', 'Safety'], 'employers' => ['Glass Contractors', 'Interior Firms']],
            ['title' => 'Jute Handloom Weaver', 'cat' => 'Trades', 'domain' => 'Handicraft', 'short' => 'Weaves jute fiber on a handloom to create fabrics, bags, or rugs.', 'salary' => '₹1.2L - ₹2.5L per annum', 'demand' => 'Stable', 'qual' => 'Skill Training', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Weaving', 'Loom Operation', 'Patience'], 'employers' => ['Jute Cooperatives', 'Handicraft Boards']],
            ['title' => 'Kitchen Steward', 'cat' => 'Trades', 'domain' => 'Hospitality', 'short' => 'Cleans dishes, kitchen equipment, and maintains kitchen hygiene.', 'salary' => '₹1.5L - ₹2.5L per annum', 'demand' => 'High', 'qual' => '8th/10th Pass', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Cleaning', 'Physical Stamina', 'Speed'], 'employers' => ['Hotels', 'Restaurants', 'Catering Cos']],
            ['title' => 'Lapidarist', 'cat' => 'Trades', 'domain' => 'Handicraft/Jewellery', 'short' => 'Cuts, polishes, and engraves precious stones (gems).', 'salary' => '₹2L - ₹6L per annum', 'demand' => 'Stable', 'qual' => 'Skill Training / Apprenticeship', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Gem Cutting', 'Precision', 'Attention to Detail'], 'employers' => ['Jewellery Manufacturers', 'Diamond Export Firms (Surat)']],
            ['title' => 'Leather Technologist', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Supervises the processing of animal skins and hides into leather.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Stable', 'qual' => 'Diploma/B.Tech in Leather Tech', 'stream' => 'Science', 'exams' => ['State CETs'], 'skills' => ['Tanning Processes', 'Quality Control', 'Chemical Handling'], 'employers' => ['Leather Tanneries', 'Footwear Cos']],
            ['title' => 'Light Motor Vehicle Driver', 'cat' => 'Trades', 'domain' => 'Transport', 'short' => 'Drives cars, taxis, or small delivery vans.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'High', 'qual' => 'Valid LMV License', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Safe Driving', 'Navigation', 'Customer Interaction'], 'employers' => ['Uber/Ola', 'Corporate Fleets', 'Private Employers']],
            ['title' => 'Mason (General)', 'cat' => 'Trades', 'domain' => 'Construction', 'short' => 'Lays building materials, including concrete and brick, to construct or repair surfaces/structures.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'Very High', 'qual' => 'Practical Experience / ITI Mason', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Bricklaying', 'Cement Mixing', 'Measurement'], 'employers' => ['Construction Contractors', 'Real Estate Developers']],
            ['title' => 'Mason (Stone)', 'cat' => 'Trades', 'domain' => 'Construction', 'short' => 'Cuts, shapes, and lays natural stone for building walls, floors, or monuments.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'Stable', 'qual' => 'Practical Experience', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Stone Cutting', 'Precision Laying', 'Strength'], 'employers' => ['Monument Builders', 'Luxury Real Estate Contractors']],
            ['title' => 'Mason (Tiling)', 'cat' => 'Trades', 'domain' => 'Construction', 'short' => 'Specializes in laying tiles on floors and walls.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'High', 'qual' => 'Practical Experience', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Tile Cutting', 'Grouting', 'Alignment'], 'employers' => ['Interior Contractors', 'Construction Firms']],
            ['title' => 'Master Hand Embroiderer (Hand Crafted Textiles)', 'cat' => 'Trades', 'domain' => 'Handicraft/Fashion', 'short' => 'A highly skilled artisan creating complex hand-embroidered designs (e.g., Zardozi, Aari).', 'salary' => '₹2L - ₹6L per annum', 'demand' => 'Moderate', 'qual' => 'Years of Apprenticeship/Experience', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Embroidery', 'Design Reading', 'Patience'], 'employers' => ['Designer Boutiques', 'Export Houses']],
            ['title' => 'Mechanical Fitter', 'cat' => 'Trades', 'domain' => 'Manufacturing/Maintenance', 'short' => 'Assembles, maintains, and repairs mechanical plants and machinery.', 'salary' => '₹2.5L - ₹5L per annum', 'demand' => 'High', 'qual' => 'ITI Fitter', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['Machine Maintenance', 'Tool Use', 'Reading Blueprints'], 'employers' => ['All Manufacturing Sectors', 'Railways']],
            ['title' => 'Multi Skill Technician (Electrical)', 'cat' => 'Trades', 'domain' => 'Maintenance', 'short' => 'Handles basic electrical, plumbing, and mechanical maintenance in a facility.', 'salary' => '₹2.5L - ₹5L per annum', 'demand' => 'High', 'qual' => 'ITI/Diploma', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['Electrical Repair', 'Basic Plumbing', 'Troubleshooting'], 'employers' => ['Facility Management Firms', 'Hospitals', 'Malls']],
            ['title' => 'Multi Skill Technician (Food Processing)', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Operates and maintains various machines in a food processing plant.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'Stable', 'qual' => 'ITI/Diploma in Mechanical/Food Tech', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['Machine Operation', 'Hygiene Standards', 'Basic Maintenance'], 'employers' => ['FMCG Factories']],
            ['title' => 'Oil Technologist', 'cat' => 'Trades', 'domain' => 'Manufacturing/Chemical', 'short' => 'Specializes in the extraction, processing, and refining of edible or essential oils.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Stable', 'qual' => 'B.Tech/Diploma in Oil Tech', 'stream' => 'Science', 'exams' => ['State CETs'], 'skills' => ['Chemical Processing', 'Quality Control', 'Refining'], 'employers' => ['Edible Oil Cos (Adani Wilmar)', 'Cosmetics Ind']],
            ['title' => 'Operator-Boring Machine', 'cat' => 'Trades', 'domain' => 'Manufacturing/Construction', 'short' => 'Operates machines that bore holes in metal, wood, or the ground.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'Moderate', 'qual' => 'ITI Machinist', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Machine Operation', 'Precision', 'Safety'], 'employers' => ['Manufacturing Units', 'Construction Contractors']],
            ['title' => 'Pastry Chef', 'cat' => 'Trades', 'domain' => 'Food Trades', 'short' => 'A professional cook specializing in making desserts, pastries, and breads.', 'salary' => '₹3L - ₹10L per annum', 'demand' => 'High', 'qual' => 'Diploma/Degree in Bakery/Culinary', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Baking', 'Dessert Plating', 'Creativity'], 'employers' => ['Hotels', 'High-end Bakeries', 'Cruise Ships']],
            ['title' => 'Plumber', 'cat' => 'Trades', 'domain' => 'Construction/Maintenance', 'short' => 'Installs and repairs pipes and fixtures that carry water or gas.', 'salary' => '₹2L - ₹5L per annum', 'demand' => 'Very High', 'qual' => 'ITI Plumber', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Pipe Fitting', 'Troubleshooting', 'Tool Use'], 'employers' => ['Construction Cos', 'Facility Management', 'Self-Employed (Urban Co)']],
            ['title' => 'Refrigeration Technician', 'cat' => 'Trades', 'domain' => 'Electronics Support', 'short' => 'Installs, maintains, and repairs commercial and domestic refrigeration units.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'High', 'qual' => 'ITI RAC (Refrigeration & AC)', 'stream' => 'Science/Tech', 'exams' => ['None'], 'skills' => ['HVAC Basics', 'Gas Charging', 'Electrical Repair'], 'employers' => ['Appliance Service Centers', 'Supermarkets', 'Cold Storages']],
            ['title' => 'Retail Cashier', 'cat' => 'Trades', 'domain' => 'Retail', 'short' => 'Handles cash transactions, processes payments, and assists customers at checkout.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => '12th Pass / Graduation', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['POS Systems', 'Basic Math', 'Customer Service'], 'employers' => ['Supermarkets (D-Mart)', 'Retail Chains', 'Restaurants']],
            ['title' => 'Retail Store Operations Assistant', 'cat' => 'Trades', 'domain' => 'Retail', 'short' => 'Assists in stocking shelves, maintaining inventory, and helping customers on the floor.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => '10th/12th Pass', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Merchandising', 'Customer Service', 'Physical Stamina'], 'employers' => ['Retail Brands', 'Malls', 'Supermarkets']],
            ['title' => 'Room Attendant', 'cat' => 'Trades', 'domain' => 'Hospitality', 'short' => 'Cleans and maintains hotel rooms to ensure guest comfort.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => '10th Pass / Short-term Course', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Cleaning Tech', 'Attention to Detail', 'Speed'], 'employers' => ['Hotels', 'Resorts', 'Hospitals']],
            ['title' => 'Rubber Technologist', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Develops and tests natural and synthetic rubber products.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Moderate', 'qual' => 'B.Tech/Diploma in Rubber Tech', 'stream' => 'Science (PCM)', 'exams' => ['State CETs'], 'skills' => ['Polymer Chemistry', 'Testing', 'Manufacturing'], 'employers' => ['Tyre Companies (MRF, Apollo)', 'Auto Parts']],
            ['title' => 'Self-employed E-tailer', 'cat' => 'Trades', 'domain' => 'Retail/Digital', 'short' => 'Sells products online through platforms like Amazon, Flipkart, or own website.', 'salary' => 'Variable (Profit based)', 'demand' => 'Growing', 'qual' => 'Basic Computer Knowledge', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['E-commerce Portals', 'Digital Marketing', 'Sourcing'], 'employers' => ['Self-Employed']],
            ['title' => 'Sewing Machine Operator', 'cat' => 'Trades', 'domain' => 'Manufacturing/Fashion', 'short' => 'Operates industrial sewing machines to produce garments or other textile products.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => 'Skill Training / ITI', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Machine Operation', 'Stitching', 'Speed'], 'employers' => ['Garment Factories', 'Export Houses', 'Boutiques']],
            ['title' => 'Showroom Hostess/Host', 'cat' => 'Trades', 'domain' => 'Retail/Hospitality', 'short' => 'Welcomes customers, answers basic queries, and directs them to sales staff.', 'salary' => '₹1.8L - ₹4L per annum', 'demand' => 'Stable', 'qual' => '12th Pass / Graduation', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Communication', 'Grooming', 'Customer Service'], 'employers' => ['Auto Showrooms', 'Jewelry Stores', 'High-end Retail']],
            ['title' => 'Smartphone Repair Technician', 'cat' => 'Trades', 'domain' => 'Electronics Support', 'short' => 'Diagnoses hardware/software issues and repairs mobile phones.', 'salary' => '₹2L - ₹5L per annum', 'demand' => 'Very High', 'qual' => 'Short-term Mobile Repair Course', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Micro-soldering', 'Troubleshooting', 'Software Flashing'], 'employers' => ['Service Centers', 'Self-Employed', 'Retail Shops']],
            ['title' => 'Solar and LED Technician', 'cat' => 'Trades', 'domain' => 'Renewable Energy/Electronics', 'short' => 'Installs and maintains solar panels and LED lighting systems.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'Growing', 'qual' => 'ITI Electrician/Electronics + Suryamitra Course', 'stream' => 'Science/Tech', 'exams' => ['Skill Certification'], 'skills' => ['Solar Panel Installation', 'Wiring', 'Basic Electronics'], 'employers' => ['Solar EPC Companies', 'Government Agencies (PEDA, GEDA)']],
            ['title' => 'Spa Therapist', 'cat' => 'Trades', 'domain' => 'Beauty/Wellness', 'short' => 'Provides massage, body treatments, and wellness therapies to clients.', 'salary' => '₹2L - ₹5L per annum', 'demand' => 'High', 'qual' => 'Diploma/Certificate in Spa Therapy', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Massage Tech', 'Anatomy Basics', 'Customer Service'], 'employers' => ['Luxury Spas', 'Hotels', 'Wellness Centers']],
            ['title' => 'Stone Cutter (Cutting Machine Operator) – Stone Craft', 'cat' => 'Trades', 'domain' => 'Handicraft/Construction', 'short' => 'Operates heavy machinery to cut large blocks of stone into slabs or specific shapes.', 'salary' => '₹1.8L - ₹3.5L per annum', 'demand' => 'Stable', 'qual' => 'Practical Training', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Machine Operation', 'Measurement', 'Safety'], 'employers' => ['Marble/Granite Processing Units', 'Quarries']],
            ['title' => 'Store Keeper (Construction)', 'cat' => 'Trades', 'domain' => 'Logistics/Construction', 'short' => 'Manages the inventory of materials, tools, and equipment at a construction site.', 'salary' => '₹2L - ₹4L per annum', 'demand' => 'High', 'qual' => '12th Pass / Basic Computer Knowledge', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Record Keeping', 'Inventory Management', 'Organization'], 'employers' => ['Construction Firms', 'Contractors']],
            ['title' => 'Stringing/Beading Artisan (Fashion Jewellery)', 'cat' => 'Trades', 'domain' => 'Handicraft/Fashion', 'short' => 'Creates fashion jewelry by stringing beads, pearls, or semi-precious stones.', 'salary' => '₹1.2L - ₹2.5L per annum', 'demand' => 'Stable', 'qual' => 'Practical Skill', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Manual Dexterity', 'Design Patterning', 'Patience'], 'employers' => ['Jewelry Export Houses', 'Self-Employed (Online selling)']],
            ['title' => 'Sugar Technologist', 'cat' => 'Trades', 'domain' => 'Manufacturing', 'short' => 'Manages the chemical and technical processes involved in sugar production.', 'salary' => '₹3L - ₹8L per annum', 'demand' => 'Stable', 'qual' => 'Diploma/B.Sc in Sugar Technology', 'stream' => 'Science', 'exams' => ['Institute Level Exams'], 'skills' => ['Chemical Processing', 'Quality Control', 'Factory Management'], 'employers' => ['Sugar Mills', 'Distilleries']],
            ['title' => 'Tea Taster', 'cat' => 'Trades', 'domain' => 'Food Trades/Agriculture', 'short' => 'Evaluates the quality, flavor, and aroma of various teas to determine their value and blend.', 'salary' => '₹4L - ₹15L per annum', 'demand' => 'Stable', 'qual' => 'Degree in Agriculture/Botany + Tea Tasting Course', 'stream' => 'Science preferred', 'exams' => ['None'], 'skills' => ['Sensory Evaluation', 'Palate Memory', 'Knowledge of Tea Varieties'], 'employers' => ['Tea Estates (Tata, Lipton)', 'Auction Houses']],
            ['title' => 'Tower Technician', 'cat' => 'Trades', 'domain' => 'Telecom', 'short' => 'Installs, maintains, and repairs telecom antennas and cables on tall cell towers.', 'salary' => '₹2L - ₹4.5L per annum', 'demand' => 'Moderate', 'qual' => 'ITI / Climbing Training', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Working at Heights', 'Basic Telecom Tech', 'Safety Protocols'], 'employers' => ['Telecom Infrastructure Cos (Indus Towers)']],
            ['title' => 'Trainee Chef/Assistant Cook', 'cat' => 'Trades', 'domain' => 'Food Trades', 'short' => 'Assists senior chefs with basic food preparation and kitchen duties.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'High', 'qual' => 'Culinary Diploma / Experience', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Chopping/Prep', 'Following Recipes', 'Kitchen Hygiene'], 'employers' => ['Restaurants', 'Hotels', 'Catering Cos']],
            ['title' => 'Waste Collector', 'cat' => 'Trades', 'domain' => 'Waste Management', 'short' => 'Collects solid waste and recyclables from residential or commercial areas.', 'salary' => '₹1.2L - ₹2.5L per annum', 'demand' => 'High', 'qual' => 'None', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Physical Stamina', 'Basic Sorting', 'Reliability'], 'employers' => ['Municipal Corporations', 'Private Waste Mgt Cos']],
            ['title' => 'Wood Polisher', 'cat' => 'Trades', 'domain' => 'Construction/Manufacturing', 'short' => 'Applies polish, varnish, and finishing coats to wooden furniture or surfaces.', 'salary' => '₹1.5L - ₹3L per annum', 'demand' => 'Stable', 'qual' => 'Practical Experience', 'stream' => 'Any Stream', 'exams' => ['None'], 'skills' => ['Sanding', 'Polishing Techniques', 'Attention to Detail'], 'employers' => ['Furniture Manufacturers', 'Interior Decorators']],
        ];

        foreach ($careers as $c) {
            $fieldModel = $fields[$c['cat']] ?? null;
            if (!$fieldModel) continue;

            $slug = Str::slug($c['title']);
            $roadmap = [
                "Complete 10+2 with " . $c['stream'],
                "Qualify entrance exams like " . implode(", ", $c['exams']),
                "Pursue " . $c['qual'],
                "Gain skills in " . implode(", ", $c['skills']),
                "Apply for jobs in " . implode(", ", array_slice($c['employers'], 0, 2))
            ];

            Career::firstOrCreate(
                ['slug' => $slug],
                [
                    'name' => $c['title'],
                    'field_id' => $fieldModel->id,
                    'sub_domain' => $c['domain'],
                    'description' => $c['short'],
                    'qualification' => $c['qual'],
                    'stream' => $c['stream'],
                    'salary_range' => $c['salary'],
                    'demand_level' => $c['demand'] ?? 'High',
                    'roadmap' => $roadmap,
                    'icon' => 'fa-briefcase',
                    'skills' => $c['skills'],
                    'entrance_exams' => $c['exams'],
                    'job_opportunities' => $c['employers'],
                    'image' => $slug . '.svg'
                ]
            );
        }
    }
}
